// Code generated by ent, DO NOT EDIT.

package downloadtask

import (
	"molly-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldUserID, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileID, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileName, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileSize, v))
}

// DownloadedSize applies equality check predicate on the "downloaded_size" field. It's identical to DownloadedSizeEQ.
func DownloadedSize(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldDownloadedSize, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldProgress, v))
}

// Speed applies equality check predicate on the "speed" field. It's identical to SpeedEQ.
func Speed(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldSpeed, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldURL, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldPath, v))
}

// VirtualPath applies equality check predicate on the "virtual_path" field. It's identical to VirtualPathEQ.
func VirtualPath(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldVirtualPath, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldState, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldErrorMsg, v))
}

// TargetDir applies equality check predicate on the "target_dir" field. It's identical to TargetDirEQ.
func TargetDir(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldTargetDir, v))
}

// SupportRange applies equality check predicate on the "support_range" field. It's identical to SupportRangeEQ.
func SupportRange(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldSupportRange, v))
}

// EnableEncryption applies equality check predicate on the "enable_encryption" field. It's identical to EnableEncryptionEQ.
func EnableEncryption(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldEnableEncryption, v))
}

// InfoHash applies equality check predicate on the "info_hash" field. It's identical to InfoHashEQ.
func InfoHash(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldInfoHash, v))
}

// FileIndex applies equality check predicate on the "file_index" field. It's identical to FileIndexEQ.
func FileIndex(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileIndex, v))
}

// TorrentName applies equality check predicate on the "torrent_name" field. It's identical to TorrentNameEQ.
func TorrentName(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldTorrentName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFinishedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldUserID, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDIsNil applies the IsNil predicate on the "file_id" field.
func FileIDIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldFileID))
}

// FileIDNotNil applies the NotNil predicate on the "file_id" field.
func FileIDNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldFileID))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldFileID, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldFileName, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldFileSize, v))
}

// DownloadedSizeEQ applies the EQ predicate on the "downloaded_size" field.
func DownloadedSizeEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldDownloadedSize, v))
}

// DownloadedSizeNEQ applies the NEQ predicate on the "downloaded_size" field.
func DownloadedSizeNEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldDownloadedSize, v))
}

// DownloadedSizeIn applies the In predicate on the "downloaded_size" field.
func DownloadedSizeIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldDownloadedSize, vs...))
}

// DownloadedSizeNotIn applies the NotIn predicate on the "downloaded_size" field.
func DownloadedSizeNotIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldDownloadedSize, vs...))
}

// DownloadedSizeGT applies the GT predicate on the "downloaded_size" field.
func DownloadedSizeGT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldDownloadedSize, v))
}

// DownloadedSizeGTE applies the GTE predicate on the "downloaded_size" field.
func DownloadedSizeGTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldDownloadedSize, v))
}

// DownloadedSizeLT applies the LT predicate on the "downloaded_size" field.
func DownloadedSizeLT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldDownloadedSize, v))
}

// DownloadedSizeLTE applies the LTE predicate on the "downloaded_size" field.
func DownloadedSizeLTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldDownloadedSize, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldProgress, v))
}

// SpeedEQ applies the EQ predicate on the "speed" field.
func SpeedEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldSpeed, v))
}

// SpeedNEQ applies the NEQ predicate on the "speed" field.
func SpeedNEQ(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldSpeed, v))
}

// SpeedIn applies the In predicate on the "speed" field.
func SpeedIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldSpeed, vs...))
}

// SpeedNotIn applies the NotIn predicate on the "speed" field.
func SpeedNotIn(vs ...int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldSpeed, vs...))
}

// SpeedGT applies the GT predicate on the "speed" field.
func SpeedGT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldSpeed, v))
}

// SpeedGTE applies the GTE predicate on the "speed" field.
func SpeedGTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldSpeed, v))
}

// SpeedLT applies the LT predicate on the "speed" field.
func SpeedLT(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldSpeed, v))
}

// SpeedLTE applies the LTE predicate on the "speed" field.
func SpeedLTE(v int64) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldSpeed, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldURL, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldPath, v))
}

// VirtualPathEQ applies the EQ predicate on the "virtual_path" field.
func VirtualPathEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldVirtualPath, v))
}

// VirtualPathNEQ applies the NEQ predicate on the "virtual_path" field.
func VirtualPathNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldVirtualPath, v))
}

// VirtualPathIn applies the In predicate on the "virtual_path" field.
func VirtualPathIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldVirtualPath, vs...))
}

// VirtualPathNotIn applies the NotIn predicate on the "virtual_path" field.
func VirtualPathNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldVirtualPath, vs...))
}

// VirtualPathGT applies the GT predicate on the "virtual_path" field.
func VirtualPathGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldVirtualPath, v))
}

// VirtualPathGTE applies the GTE predicate on the "virtual_path" field.
func VirtualPathGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldVirtualPath, v))
}

// VirtualPathLT applies the LT predicate on the "virtual_path" field.
func VirtualPathLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldVirtualPath, v))
}

// VirtualPathLTE applies the LTE predicate on the "virtual_path" field.
func VirtualPathLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldVirtualPath, v))
}

// VirtualPathContains applies the Contains predicate on the "virtual_path" field.
func VirtualPathContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldVirtualPath, v))
}

// VirtualPathHasPrefix applies the HasPrefix predicate on the "virtual_path" field.
func VirtualPathHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldVirtualPath, v))
}

// VirtualPathHasSuffix applies the HasSuffix predicate on the "virtual_path" field.
func VirtualPathHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldVirtualPath, v))
}

// VirtualPathIsNil applies the IsNil predicate on the "virtual_path" field.
func VirtualPathIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldVirtualPath))
}

// VirtualPathNotNil applies the NotNil predicate on the "virtual_path" field.
func VirtualPathNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldVirtualPath))
}

// VirtualPathEqualFold applies the EqualFold predicate on the "virtual_path" field.
func VirtualPathEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldVirtualPath, v))
}

// VirtualPathContainsFold applies the ContainsFold predicate on the "virtual_path" field.
func VirtualPathContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldVirtualPath, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldState, v))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgIsNil applies the IsNil predicate on the "error_msg" field.
func ErrorMsgIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldErrorMsg))
}

// ErrorMsgNotNil applies the NotNil predicate on the "error_msg" field.
func ErrorMsgNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldErrorMsg))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldErrorMsg, v))
}

// TargetDirEQ applies the EQ predicate on the "target_dir" field.
func TargetDirEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldTargetDir, v))
}

// TargetDirNEQ applies the NEQ predicate on the "target_dir" field.
func TargetDirNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldTargetDir, v))
}

// TargetDirIn applies the In predicate on the "target_dir" field.
func TargetDirIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldTargetDir, vs...))
}

// TargetDirNotIn applies the NotIn predicate on the "target_dir" field.
func TargetDirNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldTargetDir, vs...))
}

// TargetDirGT applies the GT predicate on the "target_dir" field.
func TargetDirGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldTargetDir, v))
}

// TargetDirGTE applies the GTE predicate on the "target_dir" field.
func TargetDirGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldTargetDir, v))
}

// TargetDirLT applies the LT predicate on the "target_dir" field.
func TargetDirLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldTargetDir, v))
}

// TargetDirLTE applies the LTE predicate on the "target_dir" field.
func TargetDirLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldTargetDir, v))
}

// TargetDirContains applies the Contains predicate on the "target_dir" field.
func TargetDirContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldTargetDir, v))
}

// TargetDirHasPrefix applies the HasPrefix predicate on the "target_dir" field.
func TargetDirHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldTargetDir, v))
}

// TargetDirHasSuffix applies the HasSuffix predicate on the "target_dir" field.
func TargetDirHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldTargetDir, v))
}

// TargetDirIsNil applies the IsNil predicate on the "target_dir" field.
func TargetDirIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldTargetDir))
}

// TargetDirNotNil applies the NotNil predicate on the "target_dir" field.
func TargetDirNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldTargetDir))
}

// TargetDirEqualFold applies the EqualFold predicate on the "target_dir" field.
func TargetDirEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldTargetDir, v))
}

// TargetDirContainsFold applies the ContainsFold predicate on the "target_dir" field.
func TargetDirContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldTargetDir, v))
}

// SupportRangeEQ applies the EQ predicate on the "support_range" field.
func SupportRangeEQ(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldSupportRange, v))
}

// SupportRangeNEQ applies the NEQ predicate on the "support_range" field.
func SupportRangeNEQ(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldSupportRange, v))
}

// EnableEncryptionEQ applies the EQ predicate on the "enable_encryption" field.
func EnableEncryptionEQ(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldEnableEncryption, v))
}

// EnableEncryptionNEQ applies the NEQ predicate on the "enable_encryption" field.
func EnableEncryptionNEQ(v bool) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldEnableEncryption, v))
}

// InfoHashEQ applies the EQ predicate on the "info_hash" field.
func InfoHashEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldInfoHash, v))
}

// InfoHashNEQ applies the NEQ predicate on the "info_hash" field.
func InfoHashNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldInfoHash, v))
}

// InfoHashIn applies the In predicate on the "info_hash" field.
func InfoHashIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldInfoHash, vs...))
}

// InfoHashNotIn applies the NotIn predicate on the "info_hash" field.
func InfoHashNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldInfoHash, vs...))
}

// InfoHashGT applies the GT predicate on the "info_hash" field.
func InfoHashGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldInfoHash, v))
}

// InfoHashGTE applies the GTE predicate on the "info_hash" field.
func InfoHashGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldInfoHash, v))
}

// InfoHashLT applies the LT predicate on the "info_hash" field.
func InfoHashLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldInfoHash, v))
}

// InfoHashLTE applies the LTE predicate on the "info_hash" field.
func InfoHashLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldInfoHash, v))
}

// InfoHashContains applies the Contains predicate on the "info_hash" field.
func InfoHashContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldInfoHash, v))
}

// InfoHashHasPrefix applies the HasPrefix predicate on the "info_hash" field.
func InfoHashHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldInfoHash, v))
}

// InfoHashHasSuffix applies the HasSuffix predicate on the "info_hash" field.
func InfoHashHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldInfoHash, v))
}

// InfoHashIsNil applies the IsNil predicate on the "info_hash" field.
func InfoHashIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldInfoHash))
}

// InfoHashNotNil applies the NotNil predicate on the "info_hash" field.
func InfoHashNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldInfoHash))
}

// InfoHashEqualFold applies the EqualFold predicate on the "info_hash" field.
func InfoHashEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldInfoHash, v))
}

// InfoHashContainsFold applies the ContainsFold predicate on the "info_hash" field.
func InfoHashContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldInfoHash, v))
}

// FileIndexEQ applies the EQ predicate on the "file_index" field.
func FileIndexEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFileIndex, v))
}

// FileIndexNEQ applies the NEQ predicate on the "file_index" field.
func FileIndexNEQ(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldFileIndex, v))
}

// FileIndexIn applies the In predicate on the "file_index" field.
func FileIndexIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldFileIndex, vs...))
}

// FileIndexNotIn applies the NotIn predicate on the "file_index" field.
func FileIndexNotIn(vs ...int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldFileIndex, vs...))
}

// FileIndexGT applies the GT predicate on the "file_index" field.
func FileIndexGT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldFileIndex, v))
}

// FileIndexGTE applies the GTE predicate on the "file_index" field.
func FileIndexGTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldFileIndex, v))
}

// FileIndexLT applies the LT predicate on the "file_index" field.
func FileIndexLT(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldFileIndex, v))
}

// FileIndexLTE applies the LTE predicate on the "file_index" field.
func FileIndexLTE(v int) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldFileIndex, v))
}

// TorrentNameEQ applies the EQ predicate on the "torrent_name" field.
func TorrentNameEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldTorrentName, v))
}

// TorrentNameNEQ applies the NEQ predicate on the "torrent_name" field.
func TorrentNameNEQ(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldTorrentName, v))
}

// TorrentNameIn applies the In predicate on the "torrent_name" field.
func TorrentNameIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldTorrentName, vs...))
}

// TorrentNameNotIn applies the NotIn predicate on the "torrent_name" field.
func TorrentNameNotIn(vs ...string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldTorrentName, vs...))
}

// TorrentNameGT applies the GT predicate on the "torrent_name" field.
func TorrentNameGT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldTorrentName, v))
}

// TorrentNameGTE applies the GTE predicate on the "torrent_name" field.
func TorrentNameGTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldTorrentName, v))
}

// TorrentNameLT applies the LT predicate on the "torrent_name" field.
func TorrentNameLT(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldTorrentName, v))
}

// TorrentNameLTE applies the LTE predicate on the "torrent_name" field.
func TorrentNameLTE(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldTorrentName, v))
}

// TorrentNameContains applies the Contains predicate on the "torrent_name" field.
func TorrentNameContains(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContains(FieldTorrentName, v))
}

// TorrentNameHasPrefix applies the HasPrefix predicate on the "torrent_name" field.
func TorrentNameHasPrefix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasPrefix(FieldTorrentName, v))
}

// TorrentNameHasSuffix applies the HasSuffix predicate on the "torrent_name" field.
func TorrentNameHasSuffix(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldHasSuffix(FieldTorrentName, v))
}

// TorrentNameIsNil applies the IsNil predicate on the "torrent_name" field.
func TorrentNameIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldTorrentName))
}

// TorrentNameNotNil applies the NotNil predicate on the "torrent_name" field.
func TorrentNameNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldTorrentName))
}

// TorrentNameEqualFold applies the EqualFold predicate on the "torrent_name" field.
func TorrentNameEqualFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEqualFold(FieldTorrentName, v))
}

// TorrentNameContainsFold applies the ContainsFold predicate on the "torrent_name" field.
func TorrentNameContainsFold(v string) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldContainsFold(FieldTorrentName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.DownloadTask {
	return predicate.DownloadTask(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DownloadTask) predicate.DownloadTask {
	return predicate.DownloadTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DownloadTask) predicate.DownloadTask {
	return predicate.DownloadTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DownloadTask) predicate.DownloadTask {
	return predicate.DownloadTask(sql.NotPredicates(p))
}
