// Code generated by ent, DO NOT EDIT.

package disk

import (
	"molly-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldID, id))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldSize, v))
}

// DiskPath applies equality check predicate on the "disk_path" field. It's identical to DiskPathEQ.
func DiskPath(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDiskPath, v))
}

// DataPath applies equality check predicate on the "data_path" field. It's identical to DataPathEQ.
func DataPath(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDataPath, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldSize, v))
}

// DiskPathEQ applies the EQ predicate on the "disk_path" field.
func DiskPathEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDiskPath, v))
}

// DiskPathNEQ applies the NEQ predicate on the "disk_path" field.
func DiskPathNEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldDiskPath, v))
}

// DiskPathIn applies the In predicate on the "disk_path" field.
func DiskPathIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldDiskPath, vs...))
}

// DiskPathNotIn applies the NotIn predicate on the "disk_path" field.
func DiskPathNotIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldDiskPath, vs...))
}

// DiskPathGT applies the GT predicate on the "disk_path" field.
func DiskPathGT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldDiskPath, v))
}

// DiskPathGTE applies the GTE predicate on the "disk_path" field.
func DiskPathGTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldDiskPath, v))
}

// DiskPathLT applies the LT predicate on the "disk_path" field.
func DiskPathLT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldDiskPath, v))
}

// DiskPathLTE applies the LTE predicate on the "disk_path" field.
func DiskPathLTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldDiskPath, v))
}

// DiskPathContains applies the Contains predicate on the "disk_path" field.
func DiskPathContains(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContains(FieldDiskPath, v))
}

// DiskPathHasPrefix applies the HasPrefix predicate on the "disk_path" field.
func DiskPathHasPrefix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasPrefix(FieldDiskPath, v))
}

// DiskPathHasSuffix applies the HasSuffix predicate on the "disk_path" field.
func DiskPathHasSuffix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasSuffix(FieldDiskPath, v))
}

// DiskPathEqualFold applies the EqualFold predicate on the "disk_path" field.
func DiskPathEqualFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldDiskPath, v))
}

// DiskPathContainsFold applies the ContainsFold predicate on the "disk_path" field.
func DiskPathContainsFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldDiskPath, v))
}

// DataPathEQ applies the EQ predicate on the "data_path" field.
func DataPathEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDataPath, v))
}

// DataPathNEQ applies the NEQ predicate on the "data_path" field.
func DataPathNEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldDataPath, v))
}

// DataPathIn applies the In predicate on the "data_path" field.
func DataPathIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldDataPath, vs...))
}

// DataPathNotIn applies the NotIn predicate on the "data_path" field.
func DataPathNotIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldDataPath, vs...))
}

// DataPathGT applies the GT predicate on the "data_path" field.
func DataPathGT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldDataPath, v))
}

// DataPathGTE applies the GTE predicate on the "data_path" field.
func DataPathGTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldDataPath, v))
}

// DataPathLT applies the LT predicate on the "data_path" field.
func DataPathLT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldDataPath, v))
}

// DataPathLTE applies the LTE predicate on the "data_path" field.
func DataPathLTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldDataPath, v))
}

// DataPathContains applies the Contains predicate on the "data_path" field.
func DataPathContains(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContains(FieldDataPath, v))
}

// DataPathHasPrefix applies the HasPrefix predicate on the "data_path" field.
func DataPathHasPrefix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasPrefix(FieldDataPath, v))
}

// DataPathHasSuffix applies the HasSuffix predicate on the "data_path" field.
func DataPathHasSuffix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasSuffix(FieldDataPath, v))
}

// DataPathEqualFold applies the EqualFold predicate on the "data_path" field.
func DataPathEqualFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldDataPath, v))
}

// DataPathContainsFold applies the ContainsFold predicate on the "data_path" field.
func DataPathContainsFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldDataPath, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.NotPredicates(p))
}
