// Code generated by ent, DO NOT EDIT.

package uploadchunk

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the uploadchunk type in the database.
	Label = "upload_chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldMd5 holds the string denoting the md5 field in the database.
	FieldMd5 = "md5"
	// FieldPathID holds the string denoting the path_id field in the database.
	FieldPathID = "path_id"
	// Table holds the table name of the uploadchunk in the database.
	Table = "upload_chunk"
)

// Columns holds all SQL columns for uploadchunk fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldFileName,
	FieldFileSize,
	FieldMd5,
	FieldPathID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UploadChunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByMd5 orders the results by the md5 field.
func ByMd5(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMd5, opts...).ToFunc()
}

// ByPathID orders the results by the path_id field.
func ByPathID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathID, opts...).ToFunc()
}
