// Code generated by ent, DO NOT EDIT.

package grouppower

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grouppower type in the database.
	Label = "group_power"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPowerID holds the string denoting the power_id field in the database.
	FieldPowerID = "power_id"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgePower holds the string denoting the power edge name in mutations.
	EdgePower = "power"
	// Table holds the table name of the grouppower in the database.
	Table = "group_power"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "group_power"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// PowerTable is the table that holds the power relation/edge.
	PowerTable = "group_power"
	// PowerInverseTable is the table name for the Power entity.
	// It exists in this package in order to avoid circular dependency with the "power" package.
	PowerInverseTable = "power"
	// PowerColumn is the table column denoting the power relation/edge.
	PowerColumn = "power_id"
)

// Columns holds all SQL columns for grouppower fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldPowerID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the GroupPower queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPowerID orders the results by the power_id field.
func ByPowerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPowerID, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByPowerField orders the results by power field.
func ByPowerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPowerStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newPowerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PowerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PowerTable, PowerColumn),
	)
}
