// Code generated by ent, DO NOT EDIT.

package s3multipartpart

import (
	"molly-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldID, id))
}

// UploadID applies equality check predicate on the "upload_id" field. It's identical to UploadIDEQ.
func UploadID(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldUploadID, v))
}

// PartNumber applies equality check predicate on the "part_number" field. It's identical to PartNumberEQ.
func PartNumber(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldPartNumber, v))
}

// Etag applies equality check predicate on the "etag" field. It's identical to EtagEQ.
func Etag(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldEtag, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldSize, v))
}

// ChunkPath applies equality check predicate on the "chunk_path" field. It's identical to ChunkPathEQ.
func ChunkPath(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldChunkPath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldCreatedAt, v))
}

// UploadIDEQ applies the EQ predicate on the "upload_id" field.
func UploadIDEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldUploadID, v))
}

// UploadIDNEQ applies the NEQ predicate on the "upload_id" field.
func UploadIDNEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldUploadID, v))
}

// UploadIDIn applies the In predicate on the "upload_id" field.
func UploadIDIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldUploadID, vs...))
}

// UploadIDNotIn applies the NotIn predicate on the "upload_id" field.
func UploadIDNotIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldUploadID, vs...))
}

// UploadIDGT applies the GT predicate on the "upload_id" field.
func UploadIDGT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldUploadID, v))
}

// UploadIDGTE applies the GTE predicate on the "upload_id" field.
func UploadIDGTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldUploadID, v))
}

// UploadIDLT applies the LT predicate on the "upload_id" field.
func UploadIDLT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldUploadID, v))
}

// UploadIDLTE applies the LTE predicate on the "upload_id" field.
func UploadIDLTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldUploadID, v))
}

// UploadIDContains applies the Contains predicate on the "upload_id" field.
func UploadIDContains(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContains(FieldUploadID, v))
}

// UploadIDHasPrefix applies the HasPrefix predicate on the "upload_id" field.
func UploadIDHasPrefix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasPrefix(FieldUploadID, v))
}

// UploadIDHasSuffix applies the HasSuffix predicate on the "upload_id" field.
func UploadIDHasSuffix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasSuffix(FieldUploadID, v))
}

// UploadIDEqualFold applies the EqualFold predicate on the "upload_id" field.
func UploadIDEqualFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEqualFold(FieldUploadID, v))
}

// UploadIDContainsFold applies the ContainsFold predicate on the "upload_id" field.
func UploadIDContainsFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContainsFold(FieldUploadID, v))
}

// PartNumberEQ applies the EQ predicate on the "part_number" field.
func PartNumberEQ(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldPartNumber, v))
}

// PartNumberNEQ applies the NEQ predicate on the "part_number" field.
func PartNumberNEQ(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldPartNumber, v))
}

// PartNumberIn applies the In predicate on the "part_number" field.
func PartNumberIn(vs ...int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldPartNumber, vs...))
}

// PartNumberNotIn applies the NotIn predicate on the "part_number" field.
func PartNumberNotIn(vs ...int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldPartNumber, vs...))
}

// PartNumberGT applies the GT predicate on the "part_number" field.
func PartNumberGT(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldPartNumber, v))
}

// PartNumberGTE applies the GTE predicate on the "part_number" field.
func PartNumberGTE(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldPartNumber, v))
}

// PartNumberLT applies the LT predicate on the "part_number" field.
func PartNumberLT(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldPartNumber, v))
}

// PartNumberLTE applies the LTE predicate on the "part_number" field.
func PartNumberLTE(v int) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldPartNumber, v))
}

// EtagEQ applies the EQ predicate on the "etag" field.
func EtagEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldEtag, v))
}

// EtagNEQ applies the NEQ predicate on the "etag" field.
func EtagNEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldEtag, v))
}

// EtagIn applies the In predicate on the "etag" field.
func EtagIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldEtag, vs...))
}

// EtagNotIn applies the NotIn predicate on the "etag" field.
func EtagNotIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldEtag, vs...))
}

// EtagGT applies the GT predicate on the "etag" field.
func EtagGT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldEtag, v))
}

// EtagGTE applies the GTE predicate on the "etag" field.
func EtagGTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldEtag, v))
}

// EtagLT applies the LT predicate on the "etag" field.
func EtagLT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldEtag, v))
}

// EtagLTE applies the LTE predicate on the "etag" field.
func EtagLTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldEtag, v))
}

// EtagContains applies the Contains predicate on the "etag" field.
func EtagContains(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContains(FieldEtag, v))
}

// EtagHasPrefix applies the HasPrefix predicate on the "etag" field.
func EtagHasPrefix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasPrefix(FieldEtag, v))
}

// EtagHasSuffix applies the HasSuffix predicate on the "etag" field.
func EtagHasSuffix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasSuffix(FieldEtag, v))
}

// EtagEqualFold applies the EqualFold predicate on the "etag" field.
func EtagEqualFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEqualFold(FieldEtag, v))
}

// EtagContainsFold applies the ContainsFold predicate on the "etag" field.
func EtagContainsFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContainsFold(FieldEtag, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldSize, v))
}

// ChunkPathEQ applies the EQ predicate on the "chunk_path" field.
func ChunkPathEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldChunkPath, v))
}

// ChunkPathNEQ applies the NEQ predicate on the "chunk_path" field.
func ChunkPathNEQ(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldChunkPath, v))
}

// ChunkPathIn applies the In predicate on the "chunk_path" field.
func ChunkPathIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldChunkPath, vs...))
}

// ChunkPathNotIn applies the NotIn predicate on the "chunk_path" field.
func ChunkPathNotIn(vs ...string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldChunkPath, vs...))
}

// ChunkPathGT applies the GT predicate on the "chunk_path" field.
func ChunkPathGT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldChunkPath, v))
}

// ChunkPathGTE applies the GTE predicate on the "chunk_path" field.
func ChunkPathGTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldChunkPath, v))
}

// ChunkPathLT applies the LT predicate on the "chunk_path" field.
func ChunkPathLT(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldChunkPath, v))
}

// ChunkPathLTE applies the LTE predicate on the "chunk_path" field.
func ChunkPathLTE(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldChunkPath, v))
}

// ChunkPathContains applies the Contains predicate on the "chunk_path" field.
func ChunkPathContains(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContains(FieldChunkPath, v))
}

// ChunkPathHasPrefix applies the HasPrefix predicate on the "chunk_path" field.
func ChunkPathHasPrefix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasPrefix(FieldChunkPath, v))
}

// ChunkPathHasSuffix applies the HasSuffix predicate on the "chunk_path" field.
func ChunkPathHasSuffix(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldHasSuffix(FieldChunkPath, v))
}

// ChunkPathIsNil applies the IsNil predicate on the "chunk_path" field.
func ChunkPathIsNil() predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIsNull(FieldChunkPath))
}

// ChunkPathNotNil applies the NotNil predicate on the "chunk_path" field.
func ChunkPathNotNil() predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotNull(FieldChunkPath))
}

// ChunkPathEqualFold applies the EqualFold predicate on the "chunk_path" field.
func ChunkPathEqualFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEqualFold(FieldChunkPath, v))
}

// ChunkPathContainsFold applies the ContainsFold predicate on the "chunk_path" field.
func ChunkPathContainsFold(v string) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldContainsFold(FieldChunkPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.S3MultipartPart) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.S3MultipartPart) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.S3MultipartPart) predicate.S3MultipartPart {
	return predicate.S3MultipartPart(sql.NotPredicates(p))
}
