// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"molly-server/ent/migrate"

	"molly-server/ent/drive"
	"molly-server/ent/entry"
	"molly-server/ent/uploadpart"
	"molly-server/ent/uploadsession"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Drive is the client for interacting with the Drive builders.
	Drive *DriveClient
	// Entry is the client for interacting with the Entry builders.
	Entry *EntryClient
	// UploadPart is the client for interacting with the UploadPart builders.
	UploadPart *UploadPartClient
	// UploadSession is the client for interacting with the UploadSession builders.
	UploadSession *UploadSessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Drive = NewDriveClient(c.config)
	c.Entry = NewEntryClient(c.config)
	c.UploadPart = NewUploadPartClient(c.config)
	c.UploadSession = NewUploadSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Drive:         NewDriveClient(cfg),
		Entry:         NewEntryClient(cfg),
		UploadPart:    NewUploadPartClient(cfg),
		UploadSession: NewUploadSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Drive:         NewDriveClient(cfg),
		Entry:         NewEntryClient(cfg),
		UploadPart:    NewUploadPartClient(cfg),
		UploadSession: NewUploadSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Drive.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Drive.Use(hooks...)
	c.Entry.Use(hooks...)
	c.UploadPart.Use(hooks...)
	c.UploadSession.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Drive.Intercept(interceptors...)
	c.Entry.Intercept(interceptors...)
	c.UploadPart.Intercept(interceptors...)
	c.UploadSession.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DriveMutation:
		return c.Drive.mutate(ctx, m)
	case *EntryMutation:
		return c.Entry.mutate(ctx, m)
	case *UploadPartMutation:
		return c.UploadPart.mutate(ctx, m)
	case *UploadSessionMutation:
		return c.UploadSession.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DriveClient is a client for the Drive schema.
type DriveClient struct {
	config
}

// NewDriveClient returns a client for the Drive from the given config.
func NewDriveClient(c config) *DriveClient {
	return &DriveClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `drive.Hooks(f(g(h())))`.
func (c *DriveClient) Use(hooks ...Hook) {
	c.hooks.Drive = append(c.hooks.Drive, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `drive.Intercept(f(g(h())))`.
func (c *DriveClient) Intercept(interceptors ...Interceptor) {
	c.inters.Drive = append(c.inters.Drive, interceptors...)
}

// Create returns a builder for creating a Drive entity.
func (c *DriveClient) Create() *DriveCreate {
	mutation := newDriveMutation(c.config, OpCreate)
	return &DriveCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Drive entities.
func (c *DriveClient) CreateBulk(builders ...*DriveCreate) *DriveCreateBulk {
	return &DriveCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DriveClient) MapCreateBulk(slice any, setFunc func(*DriveCreate, int)) *DriveCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DriveCreateBulk{err: fmt.Errorf("calling to DriveClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DriveCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DriveCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Drive.
func (c *DriveClient) Update() *DriveUpdate {
	mutation := newDriveMutation(c.config, OpUpdate)
	return &DriveUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DriveClient) UpdateOne(_m *Drive) *DriveUpdateOne {
	mutation := newDriveMutation(c.config, OpUpdateOne, withDrive(_m))
	return &DriveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DriveClient) UpdateOneID(id int) *DriveUpdateOne {
	mutation := newDriveMutation(c.config, OpUpdateOne, withDriveID(id))
	return &DriveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Drive.
func (c *DriveClient) Delete() *DriveDelete {
	mutation := newDriveMutation(c.config, OpDelete)
	return &DriveDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DriveClient) DeleteOne(_m *Drive) *DriveDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DriveClient) DeleteOneID(id int) *DriveDeleteOne {
	builder := c.Delete().Where(drive.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DriveDeleteOne{builder}
}

// Query returns a query builder for Drive.
func (c *DriveClient) Query() *DriveQuery {
	return &DriveQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDrive},
		inters: c.Interceptors(),
	}
}

// Get returns a Drive entity by its id.
func (c *DriveClient) Get(ctx context.Context, id int) (*Drive, error) {
	return c.Query().Where(drive.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DriveClient) GetX(ctx context.Context, id int) *Drive {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DriveClient) Hooks() []Hook {
	return c.hooks.Drive
}

// Interceptors returns the client interceptors.
func (c *DriveClient) Interceptors() []Interceptor {
	return c.inters.Drive
}

func (c *DriveClient) mutate(ctx context.Context, m *DriveMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DriveCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DriveUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DriveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DriveDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Drive mutation op: %q", m.Op())
	}
}

// EntryClient is a client for the Entry schema.
type EntryClient struct {
	config
}

// NewEntryClient returns a client for the Entry from the given config.
func NewEntryClient(c config) *EntryClient {
	return &EntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `entry.Hooks(f(g(h())))`.
func (c *EntryClient) Use(hooks ...Hook) {
	c.hooks.Entry = append(c.hooks.Entry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `entry.Intercept(f(g(h())))`.
func (c *EntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Entry = append(c.inters.Entry, interceptors...)
}

// Create returns a builder for creating a Entry entity.
func (c *EntryClient) Create() *EntryCreate {
	mutation := newEntryMutation(c.config, OpCreate)
	return &EntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Entry entities.
func (c *EntryClient) CreateBulk(builders ...*EntryCreate) *EntryCreateBulk {
	return &EntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EntryClient) MapCreateBulk(slice any, setFunc func(*EntryCreate, int)) *EntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EntryCreateBulk{err: fmt.Errorf("calling to EntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Entry.
func (c *EntryClient) Update() *EntryUpdate {
	mutation := newEntryMutation(c.config, OpUpdate)
	return &EntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EntryClient) UpdateOne(_m *Entry) *EntryUpdateOne {
	mutation := newEntryMutation(c.config, OpUpdateOne, withEntry(_m))
	return &EntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EntryClient) UpdateOneID(id int) *EntryUpdateOne {
	mutation := newEntryMutation(c.config, OpUpdateOne, withEntryID(id))
	return &EntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Entry.
func (c *EntryClient) Delete() *EntryDelete {
	mutation := newEntryMutation(c.config, OpDelete)
	return &EntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EntryClient) DeleteOne(_m *Entry) *EntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EntryClient) DeleteOneID(id int) *EntryDeleteOne {
	builder := c.Delete().Where(entry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EntryDeleteOne{builder}
}

// Query returns a query builder for Entry.
func (c *EntryClient) Query() *EntryQuery {
	return &EntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a Entry entity by its id.
func (c *EntryClient) Get(ctx context.Context, id int) (*Entry, error) {
	return c.Query().Where(entry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EntryClient) GetX(ctx context.Context, id int) *Entry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EntryClient) Hooks() []Hook {
	return c.hooks.Entry
}

// Interceptors returns the client interceptors.
func (c *EntryClient) Interceptors() []Interceptor {
	return c.inters.Entry
}

func (c *EntryClient) mutate(ctx context.Context, m *EntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Entry mutation op: %q", m.Op())
	}
}

// UploadPartClient is a client for the UploadPart schema.
type UploadPartClient struct {
	config
}

// NewUploadPartClient returns a client for the UploadPart from the given config.
func NewUploadPartClient(c config) *UploadPartClient {
	return &UploadPartClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `uploadpart.Hooks(f(g(h())))`.
func (c *UploadPartClient) Use(hooks ...Hook) {
	c.hooks.UploadPart = append(c.hooks.UploadPart, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `uploadpart.Intercept(f(g(h())))`.
func (c *UploadPartClient) Intercept(interceptors ...Interceptor) {
	c.inters.UploadPart = append(c.inters.UploadPart, interceptors...)
}

// Create returns a builder for creating a UploadPart entity.
func (c *UploadPartClient) Create() *UploadPartCreate {
	mutation := newUploadPartMutation(c.config, OpCreate)
	return &UploadPartCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UploadPart entities.
func (c *UploadPartClient) CreateBulk(builders ...*UploadPartCreate) *UploadPartCreateBulk {
	return &UploadPartCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UploadPartClient) MapCreateBulk(slice any, setFunc func(*UploadPartCreate, int)) *UploadPartCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UploadPartCreateBulk{err: fmt.Errorf("calling to UploadPartClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UploadPartCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UploadPartCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UploadPart.
func (c *UploadPartClient) Update() *UploadPartUpdate {
	mutation := newUploadPartMutation(c.config, OpUpdate)
	return &UploadPartUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UploadPartClient) UpdateOne(_m *UploadPart) *UploadPartUpdateOne {
	mutation := newUploadPartMutation(c.config, OpUpdateOne, withUploadPart(_m))
	return &UploadPartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UploadPartClient) UpdateOneID(id int) *UploadPartUpdateOne {
	mutation := newUploadPartMutation(c.config, OpUpdateOne, withUploadPartID(id))
	return &UploadPartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UploadPart.
func (c *UploadPartClient) Delete() *UploadPartDelete {
	mutation := newUploadPartMutation(c.config, OpDelete)
	return &UploadPartDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UploadPartClient) DeleteOne(_m *UploadPart) *UploadPartDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UploadPartClient) DeleteOneID(id int) *UploadPartDeleteOne {
	builder := c.Delete().Where(uploadpart.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UploadPartDeleteOne{builder}
}

// Query returns a query builder for UploadPart.
func (c *UploadPartClient) Query() *UploadPartQuery {
	return &UploadPartQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUploadPart},
		inters: c.Interceptors(),
	}
}

// Get returns a UploadPart entity by its id.
func (c *UploadPartClient) Get(ctx context.Context, id int) (*UploadPart, error) {
	return c.Query().Where(uploadpart.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UploadPartClient) GetX(ctx context.Context, id int) *UploadPart {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UploadPartClient) Hooks() []Hook {
	return c.hooks.UploadPart
}

// Interceptors returns the client interceptors.
func (c *UploadPartClient) Interceptors() []Interceptor {
	return c.inters.UploadPart
}

func (c *UploadPartClient) mutate(ctx context.Context, m *UploadPartMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UploadPartCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UploadPartUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UploadPartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UploadPartDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UploadPart mutation op: %q", m.Op())
	}
}

// UploadSessionClient is a client for the UploadSession schema.
type UploadSessionClient struct {
	config
}

// NewUploadSessionClient returns a client for the UploadSession from the given config.
func NewUploadSessionClient(c config) *UploadSessionClient {
	return &UploadSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `uploadsession.Hooks(f(g(h())))`.
func (c *UploadSessionClient) Use(hooks ...Hook) {
	c.hooks.UploadSession = append(c.hooks.UploadSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `uploadsession.Intercept(f(g(h())))`.
func (c *UploadSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.UploadSession = append(c.inters.UploadSession, interceptors...)
}

// Create returns a builder for creating a UploadSession entity.
func (c *UploadSessionClient) Create() *UploadSessionCreate {
	mutation := newUploadSessionMutation(c.config, OpCreate)
	return &UploadSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UploadSession entities.
func (c *UploadSessionClient) CreateBulk(builders ...*UploadSessionCreate) *UploadSessionCreateBulk {
	return &UploadSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UploadSessionClient) MapCreateBulk(slice any, setFunc func(*UploadSessionCreate, int)) *UploadSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UploadSessionCreateBulk{err: fmt.Errorf("calling to UploadSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UploadSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UploadSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UploadSession.
func (c *UploadSessionClient) Update() *UploadSessionUpdate {
	mutation := newUploadSessionMutation(c.config, OpUpdate)
	return &UploadSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UploadSessionClient) UpdateOne(_m *UploadSession) *UploadSessionUpdateOne {
	mutation := newUploadSessionMutation(c.config, OpUpdateOne, withUploadSession(_m))
	return &UploadSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UploadSessionClient) UpdateOneID(id int) *UploadSessionUpdateOne {
	mutation := newUploadSessionMutation(c.config, OpUpdateOne, withUploadSessionID(id))
	return &UploadSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UploadSession.
func (c *UploadSessionClient) Delete() *UploadSessionDelete {
	mutation := newUploadSessionMutation(c.config, OpDelete)
	return &UploadSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UploadSessionClient) DeleteOne(_m *UploadSession) *UploadSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UploadSessionClient) DeleteOneID(id int) *UploadSessionDeleteOne {
	builder := c.Delete().Where(uploadsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UploadSessionDeleteOne{builder}
}

// Query returns a query builder for UploadSession.
func (c *UploadSessionClient) Query() *UploadSessionQuery {
	return &UploadSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUploadSession},
		inters: c.Interceptors(),
	}
}

// Get returns a UploadSession entity by its id.
func (c *UploadSessionClient) Get(ctx context.Context, id int) (*UploadSession, error) {
	return c.Query().Where(uploadsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UploadSessionClient) GetX(ctx context.Context, id int) *UploadSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UploadSessionClient) Hooks() []Hook {
	return c.hooks.UploadSession
}

// Interceptors returns the client interceptors.
func (c *UploadSessionClient) Interceptors() []Interceptor {
	return c.inters.UploadSession
}

func (c *UploadSessionClient) mutate(ctx context.Context, m *UploadSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UploadSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UploadSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UploadSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UploadSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UploadSession mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Drive, Entry, UploadPart, UploadSession []ent.Hook
	}
	inters struct {
		Drive, Entry, UploadPart, UploadSession []ent.Interceptor
	}
)
