// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"molly-server/ent/grouppower"
	"molly-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupPowerDelete is the builder for deleting a GroupPower entity.
type GroupPowerDelete struct {
	config
	hooks    []Hook
	mutation *GroupPowerMutation
}

// Where appends a list predicates to the GroupPowerDelete builder.
func (_d *GroupPowerDelete) Where(ps ...predicate.GroupPower) *GroupPowerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupPowerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupPowerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupPowerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouppower.Table, sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupPowerDeleteOne is the builder for deleting a single GroupPower entity.
type GroupPowerDeleteOne struct {
	_d *GroupPowerDelete
}

// Where appends a list predicates to the GroupPowerDelete builder.
func (_d *GroupPowerDeleteOne) Where(ps ...predicate.GroupPower) *GroupPowerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupPowerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouppower.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupPowerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
