// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/group"
	"molly-server/ent/grouppower"
	"molly-server/ent/power"
	"molly-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PowerUpdate is the builder for updating Power entities.
type PowerUpdate struct {
	config
	hooks    []Hook
	mutation *PowerMutation
}

// Where appends a list predicates to the PowerUpdate builder.
func (_u *PowerUpdate) Where(ps ...predicate.Power) *PowerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PowerUpdate) SetName(v string) *PowerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PowerUpdate) SetNillableName(v *string) *PowerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PowerUpdate) SetDescription(v string) *PowerUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PowerUpdate) SetNillableDescription(v *string) *PowerUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCharacteristic sets the "characteristic" field.
func (_u *PowerUpdate) SetCharacteristic(v string) *PowerUpdate {
	_u.mutation.SetCharacteristic(v)
	return _u
}

// SetNillableCharacteristic sets the "characteristic" field if the given value is not nil.
func (_u *PowerUpdate) SetNillableCharacteristic(v *string) *PowerUpdate {
	if v != nil {
		_u.SetCharacteristic(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *PowerUpdate) AddGroupIDs(ids ...int) *PowerUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *PowerUpdate) AddGroups(v ...*Group) *PowerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddGroupPowerIDs adds the "group_powers" edge to the GroupPower entity by IDs.
func (_u *PowerUpdate) AddGroupPowerIDs(ids ...int) *PowerUpdate {
	_u.mutation.AddGroupPowerIDs(ids...)
	return _u
}

// AddGroupPowers adds the "group_powers" edges to the GroupPower entity.
func (_u *PowerUpdate) AddGroupPowers(v ...*GroupPower) *PowerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupPowerIDs(ids...)
}

// Mutation returns the PowerMutation object of the builder.
func (_u *PowerUpdate) Mutation() *PowerMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *PowerUpdate) ClearGroups() *PowerUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *PowerUpdate) RemoveGroupIDs(ids ...int) *PowerUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *PowerUpdate) RemoveGroups(v ...*Group) *PowerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearGroupPowers clears all "group_powers" edges to the GroupPower entity.
func (_u *PowerUpdate) ClearGroupPowers() *PowerUpdate {
	_u.mutation.ClearGroupPowers()
	return _u
}

// RemoveGroupPowerIDs removes the "group_powers" edge to GroupPower entities by IDs.
func (_u *PowerUpdate) RemoveGroupPowerIDs(ids ...int) *PowerUpdate {
	_u.mutation.RemoveGroupPowerIDs(ids...)
	return _u
}

// RemoveGroupPowers removes "group_powers" edges to GroupPower entities.
func (_u *PowerUpdate) RemoveGroupPowers(v ...*GroupPower) *PowerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupPowerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PowerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PowerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PowerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PowerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PowerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(power.Table, power.Columns, sqlgraph.NewFieldSpec(power.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(power.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(power.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Characteristic(); ok {
		_spec.SetField(power.FieldCharacteristic, field.TypeString, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupPowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupPowersIDs(); len(nodes) > 0 && !_u.mutation.GroupPowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupPowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{power.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PowerUpdateOne is the builder for updating a single Power entity.
type PowerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PowerMutation
}

// SetName sets the "name" field.
func (_u *PowerUpdateOne) SetName(v string) *PowerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PowerUpdateOne) SetNillableName(v *string) *PowerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PowerUpdateOne) SetDescription(v string) *PowerUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PowerUpdateOne) SetNillableDescription(v *string) *PowerUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCharacteristic sets the "characteristic" field.
func (_u *PowerUpdateOne) SetCharacteristic(v string) *PowerUpdateOne {
	_u.mutation.SetCharacteristic(v)
	return _u
}

// SetNillableCharacteristic sets the "characteristic" field if the given value is not nil.
func (_u *PowerUpdateOne) SetNillableCharacteristic(v *string) *PowerUpdateOne {
	if v != nil {
		_u.SetCharacteristic(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *PowerUpdateOne) AddGroupIDs(ids ...int) *PowerUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *PowerUpdateOne) AddGroups(v ...*Group) *PowerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddGroupPowerIDs adds the "group_powers" edge to the GroupPower entity by IDs.
func (_u *PowerUpdateOne) AddGroupPowerIDs(ids ...int) *PowerUpdateOne {
	_u.mutation.AddGroupPowerIDs(ids...)
	return _u
}

// AddGroupPowers adds the "group_powers" edges to the GroupPower entity.
func (_u *PowerUpdateOne) AddGroupPowers(v ...*GroupPower) *PowerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupPowerIDs(ids...)
}

// Mutation returns the PowerMutation object of the builder.
func (_u *PowerUpdateOne) Mutation() *PowerMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *PowerUpdateOne) ClearGroups() *PowerUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *PowerUpdateOne) RemoveGroupIDs(ids ...int) *PowerUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *PowerUpdateOne) RemoveGroups(v ...*Group) *PowerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearGroupPowers clears all "group_powers" edges to the GroupPower entity.
func (_u *PowerUpdateOne) ClearGroupPowers() *PowerUpdateOne {
	_u.mutation.ClearGroupPowers()
	return _u
}

// RemoveGroupPowerIDs removes the "group_powers" edge to GroupPower entities by IDs.
func (_u *PowerUpdateOne) RemoveGroupPowerIDs(ids ...int) *PowerUpdateOne {
	_u.mutation.RemoveGroupPowerIDs(ids...)
	return _u
}

// RemoveGroupPowers removes "group_powers" edges to GroupPower entities.
func (_u *PowerUpdateOne) RemoveGroupPowers(v ...*GroupPower) *PowerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupPowerIDs(ids...)
}

// Where appends a list predicates to the PowerUpdate builder.
func (_u *PowerUpdateOne) Where(ps ...predicate.Power) *PowerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PowerUpdateOne) Select(field string, fields ...string) *PowerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Power entity.
func (_u *PowerUpdateOne) Save(ctx context.Context) (*Power, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PowerUpdateOne) SaveX(ctx context.Context) *Power {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PowerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PowerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PowerUpdateOne) sqlSave(ctx context.Context) (_node *Power, err error) {
	_spec := sqlgraph.NewUpdateSpec(power.Table, power.Columns, sqlgraph.NewFieldSpec(power.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Power.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, power.FieldID)
		for _, f := range fields {
			if !power.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != power.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(power.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(power.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Characteristic(); ok {
		_spec.SetField(power.FieldCharacteristic, field.TypeString, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   power.GroupsTable,
			Columns: power.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupPowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupPowersIDs(); len(nodes) > 0 && !_u.mutation.GroupPowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupPowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   power.GroupPowersTable,
			Columns: []string{power.GroupPowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouppower.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Power{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{power.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
