// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/predicate"
	"molly-server/ent/recycled"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecycledUpdate is the builder for updating Recycled entities.
type RecycledUpdate struct {
	config
	hooks    []Hook
	mutation *RecycledMutation
}

// Where appends a list predicates to the RecycledUpdate builder.
func (_u *RecycledUpdate) Where(ps ...predicate.Recycled) *RecycledUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RecycledUpdate) SetUserID(v string) *RecycledUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RecycledUpdate) SetNillableUserID(v *string) *RecycledUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *RecycledUpdate) SetFileID(v string) *RecycledUpdate {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *RecycledUpdate) SetNillableFileID(v *string) *RecycledUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// Mutation returns the RecycledMutation object of the builder.
func (_u *RecycledUpdate) Mutation() *RecycledMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecycledUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecycledUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecycledUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecycledUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecycledUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(recycled.Table, recycled.Columns, sqlgraph.NewFieldSpec(recycled.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(recycled.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(recycled.FieldFileID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recycled.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecycledUpdateOne is the builder for updating a single Recycled entity.
type RecycledUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecycledMutation
}

// SetUserID sets the "user_id" field.
func (_u *RecycledUpdateOne) SetUserID(v string) *RecycledUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RecycledUpdateOne) SetNillableUserID(v *string) *RecycledUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *RecycledUpdateOne) SetFileID(v string) *RecycledUpdateOne {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *RecycledUpdateOne) SetNillableFileID(v *string) *RecycledUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// Mutation returns the RecycledMutation object of the builder.
func (_u *RecycledUpdateOne) Mutation() *RecycledMutation {
	return _u.mutation
}

// Where appends a list predicates to the RecycledUpdate builder.
func (_u *RecycledUpdateOne) Where(ps ...predicate.Recycled) *RecycledUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecycledUpdateOne) Select(field string, fields ...string) *RecycledUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Recycled entity.
func (_u *RecycledUpdateOne) Save(ctx context.Context) (*Recycled, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecycledUpdateOne) SaveX(ctx context.Context) *Recycled {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecycledUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecycledUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecycledUpdateOne) sqlSave(ctx context.Context) (_node *Recycled, err error) {
	_spec := sqlgraph.NewUpdateSpec(recycled.Table, recycled.Columns, sqlgraph.NewFieldSpec(recycled.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Recycled.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recycled.FieldID)
		for _, f := range fields {
			if !recycled.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recycled.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(recycled.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(recycled.FieldFileID, field.TypeString, value)
	}
	_node = &Recycled{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recycled.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
