// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/recycled"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecycledCreate is the builder for creating a Recycled entity.
type RecycledCreate struct {
	config
	mutation *RecycledMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *RecycledCreate) SetUserID(v string) *RecycledCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *RecycledCreate) SetFileID(v string) *RecycledCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecycledCreate) SetCreatedAt(v time.Time) *RecycledCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecycledCreate) SetNillableCreatedAt(v *time.Time) *RecycledCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecycledCreate) SetID(v string) *RecycledCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecycledCreate) SetNillableID(v *string) *RecycledCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RecycledMutation object of the builder.
func (_c *RecycledCreate) Mutation() *RecycledMutation {
	return _c.mutation
}

// Save creates the Recycled in the database.
func (_c *RecycledCreate) Save(ctx context.Context) (*Recycled, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecycledCreate) SaveX(ctx context.Context) *Recycled {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecycledCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecycledCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecycledCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recycled.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := recycled.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecycledCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Recycled.user_id"`)}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "Recycled.file_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Recycled.created_at"`)}
	}
	return nil
}

func (_c *RecycledCreate) sqlSave(ctx context.Context) (*Recycled, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Recycled.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecycledCreate) createSpec() (*Recycled, *sqlgraph.CreateSpec) {
	var (
		_node = &Recycled{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recycled.Table, sqlgraph.NewFieldSpec(recycled.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(recycled.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(recycled.FieldFileID, field.TypeString, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recycled.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Recycled.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecycledUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RecycledCreate) OnConflict(opts ...sql.ConflictOption) *RecycledUpsertOne {
	_c.conflict = opts
	return &RecycledUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Recycled.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecycledCreate) OnConflictColumns(columns ...string) *RecycledUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecycledUpsertOne{
		create: _c,
	}
}

type (
	// RecycledUpsertOne is the builder for "upsert"-ing
	//  one Recycled node.
	RecycledUpsertOne struct {
		create *RecycledCreate
	}

	// RecycledUpsert is the "OnConflict" setter.
	RecycledUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *RecycledUpsert) SetUserID(v string) *RecycledUpsert {
	u.Set(recycled.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RecycledUpsert) UpdateUserID() *RecycledUpsert {
	u.SetExcluded(recycled.FieldUserID)
	return u
}

// SetFileID sets the "file_id" field.
func (u *RecycledUpsert) SetFileID(v string) *RecycledUpsert {
	u.Set(recycled.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *RecycledUpsert) UpdateFileID() *RecycledUpsert {
	u.SetExcluded(recycled.FieldFileID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Recycled.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(recycled.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RecycledUpsertOne) UpdateNewValues() *RecycledUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(recycled.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(recycled.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Recycled.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RecycledUpsertOne) Ignore() *RecycledUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecycledUpsertOne) DoNothing() *RecycledUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecycledCreate.OnConflict
// documentation for more info.
func (u *RecycledUpsertOne) Update(set func(*RecycledUpsert)) *RecycledUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecycledUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RecycledUpsertOne) SetUserID(v string) *RecycledUpsertOne {
	return u.Update(func(s *RecycledUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RecycledUpsertOne) UpdateUserID() *RecycledUpsertOne {
	return u.Update(func(s *RecycledUpsert) {
		s.UpdateUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *RecycledUpsertOne) SetFileID(v string) *RecycledUpsertOne {
	return u.Update(func(s *RecycledUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *RecycledUpsertOne) UpdateFileID() *RecycledUpsertOne {
	return u.Update(func(s *RecycledUpsert) {
		s.UpdateFileID()
	})
}

// Exec executes the query.
func (u *RecycledUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecycledCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecycledUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RecycledUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RecycledUpsertOne.ID is not supported by MySQL driver. Use RecycledUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RecycledUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RecycledCreateBulk is the builder for creating many Recycled entities in bulk.
type RecycledCreateBulk struct {
	config
	err      error
	builders []*RecycledCreate
	conflict []sql.ConflictOption
}

// Save creates the Recycled entities in the database.
func (_c *RecycledCreateBulk) Save(ctx context.Context) ([]*Recycled, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Recycled, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecycledMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecycledCreateBulk) SaveX(ctx context.Context) []*Recycled {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecycledCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecycledCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Recycled.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecycledUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RecycledCreateBulk) OnConflict(opts ...sql.ConflictOption) *RecycledUpsertBulk {
	_c.conflict = opts
	return &RecycledUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Recycled.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RecycledCreateBulk) OnConflictColumns(columns ...string) *RecycledUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RecycledUpsertBulk{
		create: _c,
	}
}

// RecycledUpsertBulk is the builder for "upsert"-ing
// a bulk of Recycled nodes.
type RecycledUpsertBulk struct {
	create *RecycledCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Recycled.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(recycled.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RecycledUpsertBulk) UpdateNewValues() *RecycledUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(recycled.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(recycled.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Recycled.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RecycledUpsertBulk) Ignore() *RecycledUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecycledUpsertBulk) DoNothing() *RecycledUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecycledCreateBulk.OnConflict
// documentation for more info.
func (u *RecycledUpsertBulk) Update(set func(*RecycledUpsert)) *RecycledUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecycledUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RecycledUpsertBulk) SetUserID(v string) *RecycledUpsertBulk {
	return u.Update(func(s *RecycledUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RecycledUpsertBulk) UpdateUserID() *RecycledUpsertBulk {
	return u.Update(func(s *RecycledUpsert) {
		s.UpdateUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *RecycledUpsertBulk) SetFileID(v string) *RecycledUpsertBulk {
	return u.Update(func(s *RecycledUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *RecycledUpsertBulk) UpdateFileID() *RecycledUpsertBulk {
	return u.Update(func(s *RecycledUpsert) {
		s.UpdateFileID()
	})
}

// Exec executes the query.
func (u *RecycledUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RecycledCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecycledCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecycledUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
