// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/s3bucketacl"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3BucketACLCreate is the builder for creating a S3BucketACL entity.
type S3BucketACLCreate struct {
	config
	mutation *S3BucketACLMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBucketName sets the "bucket_name" field.
func (_c *S3BucketACLCreate) SetBucketName(v string) *S3BucketACLCreate {
	_c.mutation.SetBucketName(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *S3BucketACLCreate) SetUserID(v string) *S3BucketACLCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetACLConfig sets the "acl_config" field.
func (_c *S3BucketACLCreate) SetACLConfig(v string) *S3BucketACLCreate {
	_c.mutation.SetACLConfig(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *S3BucketACLCreate) SetCreatedAt(v time.Time) *S3BucketACLCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *S3BucketACLCreate) SetNillableCreatedAt(v *time.Time) *S3BucketACLCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *S3BucketACLCreate) SetUpdatedAt(v time.Time) *S3BucketACLCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *S3BucketACLCreate) SetNillableUpdatedAt(v *time.Time) *S3BucketACLCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the S3BucketACLMutation object of the builder.
func (_c *S3BucketACLCreate) Mutation() *S3BucketACLMutation {
	return _c.mutation
}

// Save creates the S3BucketACL in the database.
func (_c *S3BucketACLCreate) Save(ctx context.Context) (*S3BucketACL, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *S3BucketACLCreate) SaveX(ctx context.Context) *S3BucketACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3BucketACLCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3BucketACLCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *S3BucketACLCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := s3bucketacl.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := s3bucketacl.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *S3BucketACLCreate) check() error {
	if _, ok := _c.mutation.BucketName(); !ok {
		return &ValidationError{Name: "bucket_name", err: errors.New(`ent: missing required field "S3BucketACL.bucket_name"`)}
	}
	if v, ok := _c.mutation.BucketName(); ok {
		if err := s3bucketacl.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "S3BucketACL.bucket_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "S3BucketACL.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := s3bucketacl.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "S3BucketACL.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ACLConfig(); !ok {
		return &ValidationError{Name: "acl_config", err: errors.New(`ent: missing required field "S3BucketACL.acl_config"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "S3BucketACL.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "S3BucketACL.updated_at"`)}
	}
	return nil
}

func (_c *S3BucketACLCreate) sqlSave(ctx context.Context) (*S3BucketACL, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *S3BucketACLCreate) createSpec() (*S3BucketACL, *sqlgraph.CreateSpec) {
	var (
		_node = &S3BucketACL{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(s3bucketacl.Table, sqlgraph.NewFieldSpec(s3bucketacl.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BucketName(); ok {
		_spec.SetField(s3bucketacl.FieldBucketName, field.TypeString, value)
		_node.BucketName = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(s3bucketacl.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ACLConfig(); ok {
		_spec.SetField(s3bucketacl.FieldACLConfig, field.TypeString, value)
		_node.ACLConfig = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(s3bucketacl.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(s3bucketacl.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.S3BucketACL.Create().
//		SetBucketName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.S3BucketACLUpsert) {
//			SetBucketName(v+v).
//		}).
//		Exec(ctx)
func (_c *S3BucketACLCreate) OnConflict(opts ...sql.ConflictOption) *S3BucketACLUpsertOne {
	_c.conflict = opts
	return &S3BucketACLUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *S3BucketACLCreate) OnConflictColumns(columns ...string) *S3BucketACLUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &S3BucketACLUpsertOne{
		create: _c,
	}
}

type (
	// S3BucketACLUpsertOne is the builder for "upsert"-ing
	//  one S3BucketACL node.
	S3BucketACLUpsertOne struct {
		create *S3BucketACLCreate
	}

	// S3BucketACLUpsert is the "OnConflict" setter.
	S3BucketACLUpsert struct {
		*sql.UpdateSet
	}
)

// SetBucketName sets the "bucket_name" field.
func (u *S3BucketACLUpsert) SetBucketName(v string) *S3BucketACLUpsert {
	u.Set(s3bucketacl.FieldBucketName, v)
	return u
}

// UpdateBucketName sets the "bucket_name" field to the value that was provided on create.
func (u *S3BucketACLUpsert) UpdateBucketName() *S3BucketACLUpsert {
	u.SetExcluded(s3bucketacl.FieldBucketName)
	return u
}

// SetUserID sets the "user_id" field.
func (u *S3BucketACLUpsert) SetUserID(v string) *S3BucketACLUpsert {
	u.Set(s3bucketacl.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *S3BucketACLUpsert) UpdateUserID() *S3BucketACLUpsert {
	u.SetExcluded(s3bucketacl.FieldUserID)
	return u
}

// SetACLConfig sets the "acl_config" field.
func (u *S3BucketACLUpsert) SetACLConfig(v string) *S3BucketACLUpsert {
	u.Set(s3bucketacl.FieldACLConfig, v)
	return u
}

// UpdateACLConfig sets the "acl_config" field to the value that was provided on create.
func (u *S3BucketACLUpsert) UpdateACLConfig() *S3BucketACLUpsert {
	u.SetExcluded(s3bucketacl.FieldACLConfig)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3BucketACLUpsert) SetUpdatedAt(v time.Time) *S3BucketACLUpsert {
	u.Set(s3bucketacl.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3BucketACLUpsert) UpdateUpdatedAt() *S3BucketACLUpsert {
	u.SetExcluded(s3bucketacl.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *S3BucketACLUpsertOne) UpdateNewValues() *S3BucketACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(s3bucketacl.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *S3BucketACLUpsertOne) Ignore() *S3BucketACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *S3BucketACLUpsertOne) DoNothing() *S3BucketACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the S3BucketACLCreate.OnConflict
// documentation for more info.
func (u *S3BucketACLUpsertOne) Update(set func(*S3BucketACLUpsert)) *S3BucketACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&S3BucketACLUpsert{UpdateSet: update})
	}))
	return u
}

// SetBucketName sets the "bucket_name" field.
func (u *S3BucketACLUpsertOne) SetBucketName(v string) *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetBucketName(v)
	})
}

// UpdateBucketName sets the "bucket_name" field to the value that was provided on create.
func (u *S3BucketACLUpsertOne) UpdateBucketName() *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateBucketName()
	})
}

// SetUserID sets the "user_id" field.
func (u *S3BucketACLUpsertOne) SetUserID(v string) *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *S3BucketACLUpsertOne) UpdateUserID() *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateUserID()
	})
}

// SetACLConfig sets the "acl_config" field.
func (u *S3BucketACLUpsertOne) SetACLConfig(v string) *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetACLConfig(v)
	})
}

// UpdateACLConfig sets the "acl_config" field to the value that was provided on create.
func (u *S3BucketACLUpsertOne) UpdateACLConfig() *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateACLConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3BucketACLUpsertOne) SetUpdatedAt(v time.Time) *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3BucketACLUpsertOne) UpdateUpdatedAt() *S3BucketACLUpsertOne {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *S3BucketACLUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for S3BucketACLCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *S3BucketACLUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *S3BucketACLUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *S3BucketACLUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// S3BucketACLCreateBulk is the builder for creating many S3BucketACL entities in bulk.
type S3BucketACLCreateBulk struct {
	config
	err      error
	builders []*S3BucketACLCreate
	conflict []sql.ConflictOption
}

// Save creates the S3BucketACL entities in the database.
func (_c *S3BucketACLCreateBulk) Save(ctx context.Context) ([]*S3BucketACL, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*S3BucketACL, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*S3BucketACLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *S3BucketACLCreateBulk) SaveX(ctx context.Context) []*S3BucketACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3BucketACLCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3BucketACLCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.S3BucketACL.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.S3BucketACLUpsert) {
//			SetBucketName(v+v).
//		}).
//		Exec(ctx)
func (_c *S3BucketACLCreateBulk) OnConflict(opts ...sql.ConflictOption) *S3BucketACLUpsertBulk {
	_c.conflict = opts
	return &S3BucketACLUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *S3BucketACLCreateBulk) OnConflictColumns(columns ...string) *S3BucketACLUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &S3BucketACLUpsertBulk{
		create: _c,
	}
}

// S3BucketACLUpsertBulk is the builder for "upsert"-ing
// a bulk of S3BucketACL nodes.
type S3BucketACLUpsertBulk struct {
	create *S3BucketACLCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *S3BucketACLUpsertBulk) UpdateNewValues() *S3BucketACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(s3bucketacl.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.S3BucketACL.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *S3BucketACLUpsertBulk) Ignore() *S3BucketACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *S3BucketACLUpsertBulk) DoNothing() *S3BucketACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the S3BucketACLCreateBulk.OnConflict
// documentation for more info.
func (u *S3BucketACLUpsertBulk) Update(set func(*S3BucketACLUpsert)) *S3BucketACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&S3BucketACLUpsert{UpdateSet: update})
	}))
	return u
}

// SetBucketName sets the "bucket_name" field.
func (u *S3BucketACLUpsertBulk) SetBucketName(v string) *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetBucketName(v)
	})
}

// UpdateBucketName sets the "bucket_name" field to the value that was provided on create.
func (u *S3BucketACLUpsertBulk) UpdateBucketName() *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateBucketName()
	})
}

// SetUserID sets the "user_id" field.
func (u *S3BucketACLUpsertBulk) SetUserID(v string) *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *S3BucketACLUpsertBulk) UpdateUserID() *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateUserID()
	})
}

// SetACLConfig sets the "acl_config" field.
func (u *S3BucketACLUpsertBulk) SetACLConfig(v string) *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetACLConfig(v)
	})
}

// UpdateACLConfig sets the "acl_config" field to the value that was provided on create.
func (u *S3BucketACLUpsertBulk) UpdateACLConfig() *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateACLConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3BucketACLUpsertBulk) SetUpdatedAt(v time.Time) *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3BucketACLUpsertBulk) UpdateUpdatedAt() *S3BucketACLUpsertBulk {
	return u.Update(func(s *S3BucketACLUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *S3BucketACLUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the S3BucketACLCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for S3BucketACLCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *S3BucketACLUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
