// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/s3encryptionkey"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3EncryptionKeyCreate is the builder for creating a S3EncryptionKey entity.
type S3EncryptionKeyCreate struct {
	config
	mutation *S3EncryptionKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKeyID sets the "key_id" field.
func (_c *S3EncryptionKeyCreate) SetKeyID(v string) *S3EncryptionKeyCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetKeyData sets the "key_data" field.
func (_c *S3EncryptionKeyCreate) SetKeyData(v string) *S3EncryptionKeyCreate {
	_c.mutation.SetKeyData(v)
	return _c
}

// SetAlgorithm sets the "algorithm" field.
func (_c *S3EncryptionKeyCreate) SetAlgorithm(v string) *S3EncryptionKeyCreate {
	_c.mutation.SetAlgorithm(v)
	return _c
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_c *S3EncryptionKeyCreate) SetNillableAlgorithm(v *string) *S3EncryptionKeyCreate {
	if v != nil {
		_c.SetAlgorithm(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *S3EncryptionKeyCreate) SetCreatedAt(v time.Time) *S3EncryptionKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *S3EncryptionKeyCreate) SetNillableCreatedAt(v *time.Time) *S3EncryptionKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *S3EncryptionKeyCreate) SetUpdatedAt(v time.Time) *S3EncryptionKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *S3EncryptionKeyCreate) SetNillableUpdatedAt(v *time.Time) *S3EncryptionKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the S3EncryptionKeyMutation object of the builder.
func (_c *S3EncryptionKeyCreate) Mutation() *S3EncryptionKeyMutation {
	return _c.mutation
}

// Save creates the S3EncryptionKey in the database.
func (_c *S3EncryptionKeyCreate) Save(ctx context.Context) (*S3EncryptionKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *S3EncryptionKeyCreate) SaveX(ctx context.Context) *S3EncryptionKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3EncryptionKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3EncryptionKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *S3EncryptionKeyCreate) defaults() {
	if _, ok := _c.mutation.Algorithm(); !ok {
		v := s3encryptionkey.DefaultAlgorithm
		_c.mutation.SetAlgorithm(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := s3encryptionkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := s3encryptionkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *S3EncryptionKeyCreate) check() error {
	if _, ok := _c.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`ent: missing required field "S3EncryptionKey.key_id"`)}
	}
	if v, ok := _c.mutation.KeyID(); ok {
		if err := s3encryptionkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "S3EncryptionKey.key_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyData(); !ok {
		return &ValidationError{Name: "key_data", err: errors.New(`ent: missing required field "S3EncryptionKey.key_data"`)}
	}
	if _, ok := _c.mutation.Algorithm(); !ok {
		return &ValidationError{Name: "algorithm", err: errors.New(`ent: missing required field "S3EncryptionKey.algorithm"`)}
	}
	if v, ok := _c.mutation.Algorithm(); ok {
		if err := s3encryptionkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`ent: validator failed for field "S3EncryptionKey.algorithm": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "S3EncryptionKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "S3EncryptionKey.updated_at"`)}
	}
	return nil
}

func (_c *S3EncryptionKeyCreate) sqlSave(ctx context.Context) (*S3EncryptionKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *S3EncryptionKeyCreate) createSpec() (*S3EncryptionKey, *sqlgraph.CreateSpec) {
	var (
		_node = &S3EncryptionKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(s3encryptionkey.Table, sqlgraph.NewFieldSpec(s3encryptionkey.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(s3encryptionkey.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := _c.mutation.KeyData(); ok {
		_spec.SetField(s3encryptionkey.FieldKeyData, field.TypeString, value)
		_node.KeyData = value
	}
	if value, ok := _c.mutation.Algorithm(); ok {
		_spec.SetField(s3encryptionkey.FieldAlgorithm, field.TypeString, value)
		_node.Algorithm = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(s3encryptionkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(s3encryptionkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.S3EncryptionKey.Create().
//		SetKeyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.S3EncryptionKeyUpsert) {
//			SetKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *S3EncryptionKeyCreate) OnConflict(opts ...sql.ConflictOption) *S3EncryptionKeyUpsertOne {
	_c.conflict = opts
	return &S3EncryptionKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *S3EncryptionKeyCreate) OnConflictColumns(columns ...string) *S3EncryptionKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &S3EncryptionKeyUpsertOne{
		create: _c,
	}
}

type (
	// S3EncryptionKeyUpsertOne is the builder for "upsert"-ing
	//  one S3EncryptionKey node.
	S3EncryptionKeyUpsertOne struct {
		create *S3EncryptionKeyCreate
	}

	// S3EncryptionKeyUpsert is the "OnConflict" setter.
	S3EncryptionKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetKeyID sets the "key_id" field.
func (u *S3EncryptionKeyUpsert) SetKeyID(v string) *S3EncryptionKeyUpsert {
	u.Set(s3encryptionkey.FieldKeyID, v)
	return u
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsert) UpdateKeyID() *S3EncryptionKeyUpsert {
	u.SetExcluded(s3encryptionkey.FieldKeyID)
	return u
}

// SetKeyData sets the "key_data" field.
func (u *S3EncryptionKeyUpsert) SetKeyData(v string) *S3EncryptionKeyUpsert {
	u.Set(s3encryptionkey.FieldKeyData, v)
	return u
}

// UpdateKeyData sets the "key_data" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsert) UpdateKeyData() *S3EncryptionKeyUpsert {
	u.SetExcluded(s3encryptionkey.FieldKeyData)
	return u
}

// SetAlgorithm sets the "algorithm" field.
func (u *S3EncryptionKeyUpsert) SetAlgorithm(v string) *S3EncryptionKeyUpsert {
	u.Set(s3encryptionkey.FieldAlgorithm, v)
	return u
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsert) UpdateAlgorithm() *S3EncryptionKeyUpsert {
	u.SetExcluded(s3encryptionkey.FieldAlgorithm)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3EncryptionKeyUpsert) SetUpdatedAt(v time.Time) *S3EncryptionKeyUpsert {
	u.Set(s3encryptionkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsert) UpdateUpdatedAt() *S3EncryptionKeyUpsert {
	u.SetExcluded(s3encryptionkey.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *S3EncryptionKeyUpsertOne) UpdateNewValues() *S3EncryptionKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(s3encryptionkey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *S3EncryptionKeyUpsertOne) Ignore() *S3EncryptionKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *S3EncryptionKeyUpsertOne) DoNothing() *S3EncryptionKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the S3EncryptionKeyCreate.OnConflict
// documentation for more info.
func (u *S3EncryptionKeyUpsertOne) Update(set func(*S3EncryptionKeyUpsert)) *S3EncryptionKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&S3EncryptionKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetKeyID sets the "key_id" field.
func (u *S3EncryptionKeyUpsertOne) SetKeyID(v string) *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetKeyID(v)
	})
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertOne) UpdateKeyID() *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateKeyID()
	})
}

// SetKeyData sets the "key_data" field.
func (u *S3EncryptionKeyUpsertOne) SetKeyData(v string) *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetKeyData(v)
	})
}

// UpdateKeyData sets the "key_data" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertOne) UpdateKeyData() *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateKeyData()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *S3EncryptionKeyUpsertOne) SetAlgorithm(v string) *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertOne) UpdateAlgorithm() *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3EncryptionKeyUpsertOne) SetUpdatedAt(v time.Time) *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertOne) UpdateUpdatedAt() *S3EncryptionKeyUpsertOne {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *S3EncryptionKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for S3EncryptionKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *S3EncryptionKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *S3EncryptionKeyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *S3EncryptionKeyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// S3EncryptionKeyCreateBulk is the builder for creating many S3EncryptionKey entities in bulk.
type S3EncryptionKeyCreateBulk struct {
	config
	err      error
	builders []*S3EncryptionKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the S3EncryptionKey entities in the database.
func (_c *S3EncryptionKeyCreateBulk) Save(ctx context.Context) ([]*S3EncryptionKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*S3EncryptionKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*S3EncryptionKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *S3EncryptionKeyCreateBulk) SaveX(ctx context.Context) []*S3EncryptionKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3EncryptionKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3EncryptionKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.S3EncryptionKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.S3EncryptionKeyUpsert) {
//			SetKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *S3EncryptionKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *S3EncryptionKeyUpsertBulk {
	_c.conflict = opts
	return &S3EncryptionKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *S3EncryptionKeyCreateBulk) OnConflictColumns(columns ...string) *S3EncryptionKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &S3EncryptionKeyUpsertBulk{
		create: _c,
	}
}

// S3EncryptionKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of S3EncryptionKey nodes.
type S3EncryptionKeyUpsertBulk struct {
	create *S3EncryptionKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *S3EncryptionKeyUpsertBulk) UpdateNewValues() *S3EncryptionKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(s3encryptionkey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.S3EncryptionKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *S3EncryptionKeyUpsertBulk) Ignore() *S3EncryptionKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *S3EncryptionKeyUpsertBulk) DoNothing() *S3EncryptionKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the S3EncryptionKeyCreateBulk.OnConflict
// documentation for more info.
func (u *S3EncryptionKeyUpsertBulk) Update(set func(*S3EncryptionKeyUpsert)) *S3EncryptionKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&S3EncryptionKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetKeyID sets the "key_id" field.
func (u *S3EncryptionKeyUpsertBulk) SetKeyID(v string) *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetKeyID(v)
	})
}

// UpdateKeyID sets the "key_id" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertBulk) UpdateKeyID() *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateKeyID()
	})
}

// SetKeyData sets the "key_data" field.
func (u *S3EncryptionKeyUpsertBulk) SetKeyData(v string) *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetKeyData(v)
	})
}

// UpdateKeyData sets the "key_data" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertBulk) UpdateKeyData() *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateKeyData()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *S3EncryptionKeyUpsertBulk) SetAlgorithm(v string) *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertBulk) UpdateAlgorithm() *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *S3EncryptionKeyUpsertBulk) SetUpdatedAt(v time.Time) *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *S3EncryptionKeyUpsertBulk) UpdateUpdatedAt() *S3EncryptionKeyUpsertBulk {
	return u.Update(func(s *S3EncryptionKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *S3EncryptionKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the S3EncryptionKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for S3EncryptionKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *S3EncryptionKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
