// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"molly-server/ent/predicate"
	"molly-server/ent/s3multipartpart"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3MultipartPartDelete is the builder for deleting a S3MultipartPart entity.
type S3MultipartPartDelete struct {
	config
	hooks    []Hook
	mutation *S3MultipartPartMutation
}

// Where appends a list predicates to the S3MultipartPartDelete builder.
func (_d *S3MultipartPartDelete) Where(ps ...predicate.S3MultipartPart) *S3MultipartPartDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *S3MultipartPartDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3MultipartPartDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *S3MultipartPartDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(s3multipartpart.Table, sqlgraph.NewFieldSpec(s3multipartpart.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// S3MultipartPartDeleteOne is the builder for deleting a single S3MultipartPart entity.
type S3MultipartPartDeleteOne struct {
	_d *S3MultipartPartDelete
}

// Where appends a list predicates to the S3MultipartPartDelete builder.
func (_d *S3MultipartPartDeleteOne) Where(ps ...predicate.S3MultipartPart) *S3MultipartPartDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *S3MultipartPartDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{s3multipartpart.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3MultipartPartDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
