// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/predicate"
	"molly-server/ent/s3multipartupload"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3MultipartUploadUpdate is the builder for updating S3MultipartUpload entities.
type S3MultipartUploadUpdate struct {
	config
	hooks    []Hook
	mutation *S3MultipartUploadMutation
}

// Where appends a list predicates to the S3MultipartUploadUpdate builder.
func (_u *S3MultipartUploadUpdate) Where(ps ...predicate.S3MultipartUpload) *S3MultipartUploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3MultipartUploadUpdate) SetBucketName(v string) *S3MultipartUploadUpdate {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3MultipartUploadUpdate) SetNillableBucketName(v *string) *S3MultipartUploadUpdate {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *S3MultipartUploadUpdate) SetObjectKey(v string) *S3MultipartUploadUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *S3MultipartUploadUpdate) SetNillableObjectKey(v *string) *S3MultipartUploadUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *S3MultipartUploadUpdate) SetUserID(v string) *S3MultipartUploadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *S3MultipartUploadUpdate) SetNillableUserID(v *string) *S3MultipartUploadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *S3MultipartUploadUpdate) SetMetadata(v string) *S3MultipartUploadUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *S3MultipartUploadUpdate) SetNillableMetadata(v *string) *S3MultipartUploadUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *S3MultipartUploadUpdate) ClearMetadata() *S3MultipartUploadUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStatus sets the "status" field.
func (_u *S3MultipartUploadUpdate) SetStatus(v string) *S3MultipartUploadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *S3MultipartUploadUpdate) SetNillableStatus(v *string) *S3MultipartUploadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3MultipartUploadUpdate) SetUpdatedAt(v time.Time) *S3MultipartUploadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3MultipartUploadMutation object of the builder.
func (_u *S3MultipartUploadUpdate) Mutation() *S3MultipartUploadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *S3MultipartUploadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3MultipartUploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *S3MultipartUploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3MultipartUploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3MultipartUploadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3multipartupload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3MultipartUploadUpdate) check() error {
	if v, ok := _u.mutation.BucketName(); ok {
		if err := s3multipartupload.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.bucket_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := s3multipartupload.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := s3multipartupload.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := s3multipartupload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.status": %w`, err)}
		}
	}
	return nil
}

func (_u *S3MultipartUploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3multipartupload.Table, s3multipartupload.Columns, sqlgraph.NewFieldSpec(s3multipartupload.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3multipartupload.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(s3multipartupload.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(s3multipartupload.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(s3multipartupload.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(s3multipartupload.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(s3multipartupload.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3multipartupload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3multipartupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// S3MultipartUploadUpdateOne is the builder for updating a single S3MultipartUpload entity.
type S3MultipartUploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *S3MultipartUploadMutation
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3MultipartUploadUpdateOne) SetBucketName(v string) *S3MultipartUploadUpdateOne {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3MultipartUploadUpdateOne) SetNillableBucketName(v *string) *S3MultipartUploadUpdateOne {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *S3MultipartUploadUpdateOne) SetObjectKey(v string) *S3MultipartUploadUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *S3MultipartUploadUpdateOne) SetNillableObjectKey(v *string) *S3MultipartUploadUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *S3MultipartUploadUpdateOne) SetUserID(v string) *S3MultipartUploadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *S3MultipartUploadUpdateOne) SetNillableUserID(v *string) *S3MultipartUploadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *S3MultipartUploadUpdateOne) SetMetadata(v string) *S3MultipartUploadUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *S3MultipartUploadUpdateOne) SetNillableMetadata(v *string) *S3MultipartUploadUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *S3MultipartUploadUpdateOne) ClearMetadata() *S3MultipartUploadUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStatus sets the "status" field.
func (_u *S3MultipartUploadUpdateOne) SetStatus(v string) *S3MultipartUploadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *S3MultipartUploadUpdateOne) SetNillableStatus(v *string) *S3MultipartUploadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3MultipartUploadUpdateOne) SetUpdatedAt(v time.Time) *S3MultipartUploadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3MultipartUploadMutation object of the builder.
func (_u *S3MultipartUploadUpdateOne) Mutation() *S3MultipartUploadMutation {
	return _u.mutation
}

// Where appends a list predicates to the S3MultipartUploadUpdate builder.
func (_u *S3MultipartUploadUpdateOne) Where(ps ...predicate.S3MultipartUpload) *S3MultipartUploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *S3MultipartUploadUpdateOne) Select(field string, fields ...string) *S3MultipartUploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated S3MultipartUpload entity.
func (_u *S3MultipartUploadUpdateOne) Save(ctx context.Context) (*S3MultipartUpload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3MultipartUploadUpdateOne) SaveX(ctx context.Context) *S3MultipartUpload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *S3MultipartUploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3MultipartUploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3MultipartUploadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3multipartupload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3MultipartUploadUpdateOne) check() error {
	if v, ok := _u.mutation.BucketName(); ok {
		if err := s3multipartupload.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.bucket_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := s3multipartupload.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := s3multipartupload.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := s3multipartupload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "S3MultipartUpload.status": %w`, err)}
		}
	}
	return nil
}

func (_u *S3MultipartUploadUpdateOne) sqlSave(ctx context.Context) (_node *S3MultipartUpload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3multipartupload.Table, s3multipartupload.Columns, sqlgraph.NewFieldSpec(s3multipartupload.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "S3MultipartUpload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, s3multipartupload.FieldID)
		for _, f := range fields {
			if !s3multipartupload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != s3multipartupload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3multipartupload.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(s3multipartupload.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(s3multipartupload.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(s3multipartupload.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(s3multipartupload.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(s3multipartupload.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3multipartupload.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &S3MultipartUpload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3multipartupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
