// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/predicate"
	"molly-server/ent/s3objectacl"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3ObjectACLUpdate is the builder for updating S3ObjectACL entities.
type S3ObjectACLUpdate struct {
	config
	hooks    []Hook
	mutation *S3ObjectACLMutation
}

// Where appends a list predicates to the S3ObjectACLUpdate builder.
func (_u *S3ObjectACLUpdate) Where(ps ...predicate.S3ObjectACL) *S3ObjectACLUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3ObjectACLUpdate) SetBucketName(v string) *S3ObjectACLUpdate {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3ObjectACLUpdate) SetNillableBucketName(v *string) *S3ObjectACLUpdate {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *S3ObjectACLUpdate) SetObjectKey(v string) *S3ObjectACLUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *S3ObjectACLUpdate) SetNillableObjectKey(v *string) *S3ObjectACLUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetVersionID sets the "version_id" field.
func (_u *S3ObjectACLUpdate) SetVersionID(v string) *S3ObjectACLUpdate {
	_u.mutation.SetVersionID(v)
	return _u
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_u *S3ObjectACLUpdate) SetNillableVersionID(v *string) *S3ObjectACLUpdate {
	if v != nil {
		_u.SetVersionID(*v)
	}
	return _u
}

// ClearVersionID clears the value of the "version_id" field.
func (_u *S3ObjectACLUpdate) ClearVersionID() *S3ObjectACLUpdate {
	_u.mutation.ClearVersionID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *S3ObjectACLUpdate) SetUserID(v string) *S3ObjectACLUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *S3ObjectACLUpdate) SetNillableUserID(v *string) *S3ObjectACLUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetACLConfig sets the "acl_config" field.
func (_u *S3ObjectACLUpdate) SetACLConfig(v string) *S3ObjectACLUpdate {
	_u.mutation.SetACLConfig(v)
	return _u
}

// SetNillableACLConfig sets the "acl_config" field if the given value is not nil.
func (_u *S3ObjectACLUpdate) SetNillableACLConfig(v *string) *S3ObjectACLUpdate {
	if v != nil {
		_u.SetACLConfig(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3ObjectACLUpdate) SetUpdatedAt(v time.Time) *S3ObjectACLUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3ObjectACLMutation object of the builder.
func (_u *S3ObjectACLUpdate) Mutation() *S3ObjectACLMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *S3ObjectACLUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3ObjectACLUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *S3ObjectACLUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3ObjectACLUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3ObjectACLUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3objectacl.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3ObjectACLUpdate) check() error {
	if v, ok := _u.mutation.BucketName(); ok {
		if err := s3objectacl.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.bucket_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := s3objectacl.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionID(); ok {
		if err := s3objectacl.VersionIDValidator(v); err != nil {
			return &ValidationError{Name: "version_id", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.version_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := s3objectacl.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *S3ObjectACLUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3objectacl.Table, s3objectacl.Columns, sqlgraph.NewFieldSpec(s3objectacl.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3objectacl.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(s3objectacl.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionID(); ok {
		_spec.SetField(s3objectacl.FieldVersionID, field.TypeString, value)
	}
	if _u.mutation.VersionIDCleared() {
		_spec.ClearField(s3objectacl.FieldVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(s3objectacl.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ACLConfig(); ok {
		_spec.SetField(s3objectacl.FieldACLConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3objectacl.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3objectacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// S3ObjectACLUpdateOne is the builder for updating a single S3ObjectACL entity.
type S3ObjectACLUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *S3ObjectACLMutation
}

// SetBucketName sets the "bucket_name" field.
func (_u *S3ObjectACLUpdateOne) SetBucketName(v string) *S3ObjectACLUpdateOne {
	_u.mutation.SetBucketName(v)
	return _u
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_u *S3ObjectACLUpdateOne) SetNillableBucketName(v *string) *S3ObjectACLUpdateOne {
	if v != nil {
		_u.SetBucketName(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *S3ObjectACLUpdateOne) SetObjectKey(v string) *S3ObjectACLUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *S3ObjectACLUpdateOne) SetNillableObjectKey(v *string) *S3ObjectACLUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetVersionID sets the "version_id" field.
func (_u *S3ObjectACLUpdateOne) SetVersionID(v string) *S3ObjectACLUpdateOne {
	_u.mutation.SetVersionID(v)
	return _u
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_u *S3ObjectACLUpdateOne) SetNillableVersionID(v *string) *S3ObjectACLUpdateOne {
	if v != nil {
		_u.SetVersionID(*v)
	}
	return _u
}

// ClearVersionID clears the value of the "version_id" field.
func (_u *S3ObjectACLUpdateOne) ClearVersionID() *S3ObjectACLUpdateOne {
	_u.mutation.ClearVersionID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *S3ObjectACLUpdateOne) SetUserID(v string) *S3ObjectACLUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *S3ObjectACLUpdateOne) SetNillableUserID(v *string) *S3ObjectACLUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetACLConfig sets the "acl_config" field.
func (_u *S3ObjectACLUpdateOne) SetACLConfig(v string) *S3ObjectACLUpdateOne {
	_u.mutation.SetACLConfig(v)
	return _u
}

// SetNillableACLConfig sets the "acl_config" field if the given value is not nil.
func (_u *S3ObjectACLUpdateOne) SetNillableACLConfig(v *string) *S3ObjectACLUpdateOne {
	if v != nil {
		_u.SetACLConfig(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3ObjectACLUpdateOne) SetUpdatedAt(v time.Time) *S3ObjectACLUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the S3ObjectACLMutation object of the builder.
func (_u *S3ObjectACLUpdateOne) Mutation() *S3ObjectACLMutation {
	return _u.mutation
}

// Where appends a list predicates to the S3ObjectACLUpdate builder.
func (_u *S3ObjectACLUpdateOne) Where(ps ...predicate.S3ObjectACL) *S3ObjectACLUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *S3ObjectACLUpdateOne) Select(field string, fields ...string) *S3ObjectACLUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated S3ObjectACL entity.
func (_u *S3ObjectACLUpdateOne) Save(ctx context.Context) (*S3ObjectACL, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3ObjectACLUpdateOne) SaveX(ctx context.Context) *S3ObjectACL {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *S3ObjectACLUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3ObjectACLUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3ObjectACLUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3objectacl.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3ObjectACLUpdateOne) check() error {
	if v, ok := _u.mutation.BucketName(); ok {
		if err := s3objectacl.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.bucket_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ObjectKey(); ok {
		if err := s3objectacl.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.object_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionID(); ok {
		if err := s3objectacl.VersionIDValidator(v); err != nil {
			return &ValidationError{Name: "version_id", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.version_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := s3objectacl.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "S3ObjectACL.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *S3ObjectACLUpdateOne) sqlSave(ctx context.Context) (_node *S3ObjectACL, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3objectacl.Table, s3objectacl.Columns, sqlgraph.NewFieldSpec(s3objectacl.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "S3ObjectACL.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, s3objectacl.FieldID)
		for _, f := range fields {
			if !s3objectacl.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != s3objectacl.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketName(); ok {
		_spec.SetField(s3objectacl.FieldBucketName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(s3objectacl.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionID(); ok {
		_spec.SetField(s3objectacl.FieldVersionID, field.TypeString, value)
	}
	if _u.mutation.VersionIDCleared() {
		_spec.ClearField(s3objectacl.FieldVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(s3objectacl.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ACLConfig(); ok {
		_spec.SetField(s3objectacl.FieldACLConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3objectacl.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &S3ObjectACL{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3objectacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
