// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"molly-server/ent/uploadtask"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UploadTask is the model entity for the UploadTask schema.
type UploadTask struct {
	config `json:"-"`
	// ID of the ent.
	// 预检 ID（precheck_id），前端用于断点续传标识
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// 分片大小，默认 5MB
	ChunkSize int64 `json:"chunk_size,omitempty"`
	// TotalChunks holds the value of the "total_chunks" field.
	TotalChunks int `json:"total_chunks,omitempty"`
	// UploadedChunks holds the value of the "uploaded_chunks" field.
	UploadedChunks int `json:"uploaded_chunks,omitempty"`
	// 分片签名，用于秒传检测
	ChunkSignature string `json:"chunk_signature,omitempty"`
	// 目标虚拟路径 ID
	PathID string `json:"path_id,omitempty"`
	// 服务端临时分片目录
	TempDir string `json:"temp_dir,omitempty"`
	// pending | uploading | completed | failed | aborted
	Status string `json:"status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 任务过期时间，默认 7 天后自动清理
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UploadTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uploadtask.FieldFileSize, uploadtask.FieldChunkSize, uploadtask.FieldTotalChunks, uploadtask.FieldUploadedChunks:
			values[i] = new(sql.NullInt64)
		case uploadtask.FieldID, uploadtask.FieldUserID, uploadtask.FieldFileName, uploadtask.FieldChunkSignature, uploadtask.FieldPathID, uploadtask.FieldTempDir, uploadtask.FieldStatus, uploadtask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case uploadtask.FieldCreatedAt, uploadtask.FieldUpdatedAt, uploadtask.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UploadTask fields.
func (_m *UploadTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uploadtask.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case uploadtask.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case uploadtask.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case uploadtask.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case uploadtask.FieldChunkSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_size", values[i])
			} else if value.Valid {
				_m.ChunkSize = value.Int64
			}
		case uploadtask.FieldTotalChunks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_chunks", values[i])
			} else if value.Valid {
				_m.TotalChunks = int(value.Int64)
			}
		case uploadtask.FieldUploadedChunks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_chunks", values[i])
			} else if value.Valid {
				_m.UploadedChunks = int(value.Int64)
			}
		case uploadtask.FieldChunkSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_signature", values[i])
			} else if value.Valid {
				_m.ChunkSignature = value.String
			}
		case uploadtask.FieldPathID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path_id", values[i])
			} else if value.Valid {
				_m.PathID = value.String
			}
		case uploadtask.FieldTempDir:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field temp_dir", values[i])
			} else if value.Valid {
				_m.TempDir = value.String
			}
		case uploadtask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case uploadtask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case uploadtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uploadtask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case uploadtask.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UploadTask.
// This includes values selected through modifiers, order, etc.
func (_m *UploadTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UploadTask.
// Note that you need to call UploadTask.Unwrap() before calling this method if this UploadTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UploadTask) Update() *UploadTaskUpdateOne {
	return NewUploadTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UploadTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UploadTask) Unwrap() *UploadTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UploadTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UploadTask) String() string {
	var builder strings.Builder
	builder.WriteString("UploadTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("chunk_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChunkSize))
	builder.WriteString(", ")
	builder.WriteString("total_chunks=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalChunks))
	builder.WriteString(", ")
	builder.WriteString("uploaded_chunks=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadedChunks))
	builder.WriteString(", ")
	builder.WriteString("chunk_signature=")
	builder.WriteString(_m.ChunkSignature)
	builder.WriteString(", ")
	builder.WriteString("path_id=")
	builder.WriteString(_m.PathID)
	builder.WriteString(", ")
	builder.WriteString("temp_dir=")
	builder.WriteString(_m.TempDir)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UploadTasks is a parsable slice of UploadTask.
type UploadTasks []*UploadTask
