// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/uploadtask"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadTaskCreate is the builder for creating a UploadTask entity.
type UploadTaskCreate struct {
	config
	mutation *UploadTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UploadTaskCreate) SetUserID(v string) *UploadTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *UploadTaskCreate) SetFileName(v string) *UploadTaskCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *UploadTaskCreate) SetFileSize(v int64) *UploadTaskCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetChunkSize sets the "chunk_size" field.
func (_c *UploadTaskCreate) SetChunkSize(v int64) *UploadTaskCreate {
	_c.mutation.SetChunkSize(v)
	return _c
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableChunkSize(v *int64) *UploadTaskCreate {
	if v != nil {
		_c.SetChunkSize(*v)
	}
	return _c
}

// SetTotalChunks sets the "total_chunks" field.
func (_c *UploadTaskCreate) SetTotalChunks(v int) *UploadTaskCreate {
	_c.mutation.SetTotalChunks(v)
	return _c
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (_c *UploadTaskCreate) SetUploadedChunks(v int) *UploadTaskCreate {
	_c.mutation.SetUploadedChunks(v)
	return _c
}

// SetNillableUploadedChunks sets the "uploaded_chunks" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableUploadedChunks(v *int) *UploadTaskCreate {
	if v != nil {
		_c.SetUploadedChunks(*v)
	}
	return _c
}

// SetChunkSignature sets the "chunk_signature" field.
func (_c *UploadTaskCreate) SetChunkSignature(v string) *UploadTaskCreate {
	_c.mutation.SetChunkSignature(v)
	return _c
}

// SetNillableChunkSignature sets the "chunk_signature" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableChunkSignature(v *string) *UploadTaskCreate {
	if v != nil {
		_c.SetChunkSignature(*v)
	}
	return _c
}

// SetPathID sets the "path_id" field.
func (_c *UploadTaskCreate) SetPathID(v string) *UploadTaskCreate {
	_c.mutation.SetPathID(v)
	return _c
}

// SetTempDir sets the "temp_dir" field.
func (_c *UploadTaskCreate) SetTempDir(v string) *UploadTaskCreate {
	_c.mutation.SetTempDir(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UploadTaskCreate) SetStatus(v string) *UploadTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableStatus(v *string) *UploadTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *UploadTaskCreate) SetErrorMessage(v string) *UploadTaskCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableErrorMessage(v *string) *UploadTaskCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UploadTaskCreate) SetCreatedAt(v time.Time) *UploadTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableCreatedAt(v *time.Time) *UploadTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UploadTaskCreate) SetUpdatedAt(v time.Time) *UploadTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableUpdatedAt(v *time.Time) *UploadTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UploadTaskCreate) SetExpiresAt(v time.Time) *UploadTaskCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UploadTaskCreate) SetID(v string) *UploadTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UploadTaskCreate) SetNillableID(v *string) *UploadTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_c *UploadTaskCreate) Mutation() *UploadTaskMutation {
	return _c.mutation
}

// Save creates the UploadTask in the database.
func (_c *UploadTaskCreate) Save(ctx context.Context) (*UploadTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadTaskCreate) SaveX(ctx context.Context) *UploadTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadTaskCreate) defaults() {
	if _, ok := _c.mutation.ChunkSize(); !ok {
		v := uploadtask.DefaultChunkSize
		_c.mutation.SetChunkSize(v)
	}
	if _, ok := _c.mutation.UploadedChunks(); !ok {
		v := uploadtask.DefaultUploadedChunks
		_c.mutation.SetUploadedChunks(v)
	}
	if _, ok := _c.mutation.ChunkSignature(); !ok {
		v := uploadtask.DefaultChunkSignature
		_c.mutation.SetChunkSignature(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := uploadtask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := uploadtask.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uploadtask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := uploadtask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uploadtask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadTaskCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UploadTask.user_id"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "UploadTask.file_name"`)}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "UploadTask.file_size"`)}
	}
	if _, ok := _c.mutation.ChunkSize(); !ok {
		return &ValidationError{Name: "chunk_size", err: errors.New(`ent: missing required field "UploadTask.chunk_size"`)}
	}
	if _, ok := _c.mutation.TotalChunks(); !ok {
		return &ValidationError{Name: "total_chunks", err: errors.New(`ent: missing required field "UploadTask.total_chunks"`)}
	}
	if _, ok := _c.mutation.UploadedChunks(); !ok {
		return &ValidationError{Name: "uploaded_chunks", err: errors.New(`ent: missing required field "UploadTask.uploaded_chunks"`)}
	}
	if _, ok := _c.mutation.PathID(); !ok {
		return &ValidationError{Name: "path_id", err: errors.New(`ent: missing required field "UploadTask.path_id"`)}
	}
	if _, ok := _c.mutation.TempDir(); !ok {
		return &ValidationError{Name: "temp_dir", err: errors.New(`ent: missing required field "UploadTask.temp_dir"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UploadTask.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UploadTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UploadTask.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UploadTask.expires_at"`)}
	}
	return nil
}

func (_c *UploadTaskCreate) sqlSave(ctx context.Context) (*UploadTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UploadTask.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadTaskCreate) createSpec() (*UploadTask, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadtask.Table, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(uploadtask.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(uploadtask.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(uploadtask.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.ChunkSize(); ok {
		_spec.SetField(uploadtask.FieldChunkSize, field.TypeInt64, value)
		_node.ChunkSize = value
	}
	if value, ok := _c.mutation.TotalChunks(); ok {
		_spec.SetField(uploadtask.FieldTotalChunks, field.TypeInt, value)
		_node.TotalChunks = value
	}
	if value, ok := _c.mutation.UploadedChunks(); ok {
		_spec.SetField(uploadtask.FieldUploadedChunks, field.TypeInt, value)
		_node.UploadedChunks = value
	}
	if value, ok := _c.mutation.ChunkSignature(); ok {
		_spec.SetField(uploadtask.FieldChunkSignature, field.TypeString, value)
		_node.ChunkSignature = value
	}
	if value, ok := _c.mutation.PathID(); ok {
		_spec.SetField(uploadtask.FieldPathID, field.TypeString, value)
		_node.PathID = value
	}
	if value, ok := _c.mutation.TempDir(); ok {
		_spec.SetField(uploadtask.FieldTempDir, field.TypeString, value)
		_node.TempDir = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(uploadtask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(uploadtask.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uploadtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadtask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadtask.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadTask.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadTaskUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadTaskCreate) OnConflict(opts ...sql.ConflictOption) *UploadTaskUpsertOne {
	_c.conflict = opts
	return &UploadTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadTaskCreate) OnConflictColumns(columns ...string) *UploadTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadTaskUpsertOne{
		create: _c,
	}
}

type (
	// UploadTaskUpsertOne is the builder for "upsert"-ing
	//  one UploadTask node.
	UploadTaskUpsertOne struct {
		create *UploadTaskCreate
	}

	// UploadTaskUpsert is the "OnConflict" setter.
	UploadTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UploadTaskUpsert) SetUserID(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateUserID() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldUserID)
	return u
}

// SetFileName sets the "file_name" field.
func (u *UploadTaskUpsert) SetFileName(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateFileName() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldFileName)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *UploadTaskUpsert) SetFileSize(v int64) *UploadTaskUpsert {
	u.Set(uploadtask.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateFileSize() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *UploadTaskUpsert) AddFileSize(v int64) *UploadTaskUpsert {
	u.Add(uploadtask.FieldFileSize, v)
	return u
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadTaskUpsert) SetChunkSize(v int64) *UploadTaskUpsert {
	u.Set(uploadtask.FieldChunkSize, v)
	return u
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateChunkSize() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldChunkSize)
	return u
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadTaskUpsert) AddChunkSize(v int64) *UploadTaskUpsert {
	u.Add(uploadtask.FieldChunkSize, v)
	return u
}

// SetTotalChunks sets the "total_chunks" field.
func (u *UploadTaskUpsert) SetTotalChunks(v int) *UploadTaskUpsert {
	u.Set(uploadtask.FieldTotalChunks, v)
	return u
}

// UpdateTotalChunks sets the "total_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateTotalChunks() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldTotalChunks)
	return u
}

// AddTotalChunks adds v to the "total_chunks" field.
func (u *UploadTaskUpsert) AddTotalChunks(v int) *UploadTaskUpsert {
	u.Add(uploadtask.FieldTotalChunks, v)
	return u
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (u *UploadTaskUpsert) SetUploadedChunks(v int) *UploadTaskUpsert {
	u.Set(uploadtask.FieldUploadedChunks, v)
	return u
}

// UpdateUploadedChunks sets the "uploaded_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateUploadedChunks() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldUploadedChunks)
	return u
}

// AddUploadedChunks adds v to the "uploaded_chunks" field.
func (u *UploadTaskUpsert) AddUploadedChunks(v int) *UploadTaskUpsert {
	u.Add(uploadtask.FieldUploadedChunks, v)
	return u
}

// SetChunkSignature sets the "chunk_signature" field.
func (u *UploadTaskUpsert) SetChunkSignature(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldChunkSignature, v)
	return u
}

// UpdateChunkSignature sets the "chunk_signature" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateChunkSignature() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldChunkSignature)
	return u
}

// ClearChunkSignature clears the value of the "chunk_signature" field.
func (u *UploadTaskUpsert) ClearChunkSignature() *UploadTaskUpsert {
	u.SetNull(uploadtask.FieldChunkSignature)
	return u
}

// SetPathID sets the "path_id" field.
func (u *UploadTaskUpsert) SetPathID(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldPathID, v)
	return u
}

// UpdatePathID sets the "path_id" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdatePathID() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldPathID)
	return u
}

// SetTempDir sets the "temp_dir" field.
func (u *UploadTaskUpsert) SetTempDir(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldTempDir, v)
	return u
}

// UpdateTempDir sets the "temp_dir" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateTempDir() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldTempDir)
	return u
}

// SetStatus sets the "status" field.
func (u *UploadTaskUpsert) SetStatus(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateStatus() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldStatus)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *UploadTaskUpsert) SetErrorMessage(v string) *UploadTaskUpsert {
	u.Set(uploadtask.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateErrorMessage() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UploadTaskUpsert) ClearErrorMessage() *UploadTaskUpsert {
	u.SetNull(uploadtask.FieldErrorMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadTaskUpsert) SetUpdatedAt(v time.Time) *UploadTaskUpsert {
	u.Set(uploadtask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateUpdatedAt() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldUpdatedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadTaskUpsert) SetExpiresAt(v time.Time) *UploadTaskUpsert {
	u.Set(uploadtask.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadTaskUpsert) UpdateExpiresAt() *UploadTaskUpsert {
	u.SetExcluded(uploadtask.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uploadtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UploadTaskUpsertOne) UpdateNewValues() *UploadTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(uploadtask.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uploadtask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UploadTaskUpsertOne) Ignore() *UploadTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadTaskUpsertOne) DoNothing() *UploadTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadTaskCreate.OnConflict
// documentation for more info.
func (u *UploadTaskUpsertOne) Update(set func(*UploadTaskUpsert)) *UploadTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UploadTaskUpsertOne) SetUserID(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateUserID() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetFileName sets the "file_name" field.
func (u *UploadTaskUpsertOne) SetFileName(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateFileName() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *UploadTaskUpsertOne) SetFileSize(v int64) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *UploadTaskUpsertOne) AddFileSize(v int64) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateFileSize() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateFileSize()
	})
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadTaskUpsertOne) SetChunkSize(v int64) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetChunkSize(v)
	})
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadTaskUpsertOne) AddChunkSize(v int64) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddChunkSize(v)
	})
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateChunkSize() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateChunkSize()
	})
}

// SetTotalChunks sets the "total_chunks" field.
func (u *UploadTaskUpsertOne) SetTotalChunks(v int) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetTotalChunks(v)
	})
}

// AddTotalChunks adds v to the "total_chunks" field.
func (u *UploadTaskUpsertOne) AddTotalChunks(v int) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddTotalChunks(v)
	})
}

// UpdateTotalChunks sets the "total_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateTotalChunks() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateTotalChunks()
	})
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (u *UploadTaskUpsertOne) SetUploadedChunks(v int) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUploadedChunks(v)
	})
}

// AddUploadedChunks adds v to the "uploaded_chunks" field.
func (u *UploadTaskUpsertOne) AddUploadedChunks(v int) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddUploadedChunks(v)
	})
}

// UpdateUploadedChunks sets the "uploaded_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateUploadedChunks() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUploadedChunks()
	})
}

// SetChunkSignature sets the "chunk_signature" field.
func (u *UploadTaskUpsertOne) SetChunkSignature(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetChunkSignature(v)
	})
}

// UpdateChunkSignature sets the "chunk_signature" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateChunkSignature() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateChunkSignature()
	})
}

// ClearChunkSignature clears the value of the "chunk_signature" field.
func (u *UploadTaskUpsertOne) ClearChunkSignature() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.ClearChunkSignature()
	})
}

// SetPathID sets the "path_id" field.
func (u *UploadTaskUpsertOne) SetPathID(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetPathID(v)
	})
}

// UpdatePathID sets the "path_id" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdatePathID() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdatePathID()
	})
}

// SetTempDir sets the "temp_dir" field.
func (u *UploadTaskUpsertOne) SetTempDir(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetTempDir(v)
	})
}

// UpdateTempDir sets the "temp_dir" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateTempDir() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateTempDir()
	})
}

// SetStatus sets the "status" field.
func (u *UploadTaskUpsertOne) SetStatus(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateStatus() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UploadTaskUpsertOne) SetErrorMessage(v string) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateErrorMessage() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UploadTaskUpsertOne) ClearErrorMessage() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadTaskUpsertOne) SetUpdatedAt(v time.Time) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateUpdatedAt() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadTaskUpsertOne) SetExpiresAt(v time.Time) *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadTaskUpsertOne) UpdateExpiresAt() *UploadTaskUpsertOne {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *UploadTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UploadTaskUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UploadTaskUpsertOne.ID is not supported by MySQL driver. Use UploadTaskUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UploadTaskUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UploadTaskCreateBulk is the builder for creating many UploadTask entities in bulk.
type UploadTaskCreateBulk struct {
	config
	err      error
	builders []*UploadTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the UploadTask entities in the database.
func (_c *UploadTaskCreateBulk) Save(ctx context.Context) ([]*UploadTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadTaskCreateBulk) SaveX(ctx context.Context) []*UploadTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadTaskUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *UploadTaskUpsertBulk {
	_c.conflict = opts
	return &UploadTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadTaskCreateBulk) OnConflictColumns(columns ...string) *UploadTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadTaskUpsertBulk{
		create: _c,
	}
}

// UploadTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of UploadTask nodes.
type UploadTaskUpsertBulk struct {
	create *UploadTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uploadtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UploadTaskUpsertBulk) UpdateNewValues() *UploadTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(uploadtask.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uploadtask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UploadTaskUpsertBulk) Ignore() *UploadTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadTaskUpsertBulk) DoNothing() *UploadTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadTaskCreateBulk.OnConflict
// documentation for more info.
func (u *UploadTaskUpsertBulk) Update(set func(*UploadTaskUpsert)) *UploadTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UploadTaskUpsertBulk) SetUserID(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateUserID() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetFileName sets the "file_name" field.
func (u *UploadTaskUpsertBulk) SetFileName(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateFileName() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *UploadTaskUpsertBulk) SetFileSize(v int64) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *UploadTaskUpsertBulk) AddFileSize(v int64) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateFileSize() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateFileSize()
	})
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadTaskUpsertBulk) SetChunkSize(v int64) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetChunkSize(v)
	})
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadTaskUpsertBulk) AddChunkSize(v int64) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddChunkSize(v)
	})
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateChunkSize() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateChunkSize()
	})
}

// SetTotalChunks sets the "total_chunks" field.
func (u *UploadTaskUpsertBulk) SetTotalChunks(v int) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetTotalChunks(v)
	})
}

// AddTotalChunks adds v to the "total_chunks" field.
func (u *UploadTaskUpsertBulk) AddTotalChunks(v int) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddTotalChunks(v)
	})
}

// UpdateTotalChunks sets the "total_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateTotalChunks() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateTotalChunks()
	})
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (u *UploadTaskUpsertBulk) SetUploadedChunks(v int) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUploadedChunks(v)
	})
}

// AddUploadedChunks adds v to the "uploaded_chunks" field.
func (u *UploadTaskUpsertBulk) AddUploadedChunks(v int) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.AddUploadedChunks(v)
	})
}

// UpdateUploadedChunks sets the "uploaded_chunks" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateUploadedChunks() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUploadedChunks()
	})
}

// SetChunkSignature sets the "chunk_signature" field.
func (u *UploadTaskUpsertBulk) SetChunkSignature(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetChunkSignature(v)
	})
}

// UpdateChunkSignature sets the "chunk_signature" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateChunkSignature() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateChunkSignature()
	})
}

// ClearChunkSignature clears the value of the "chunk_signature" field.
func (u *UploadTaskUpsertBulk) ClearChunkSignature() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.ClearChunkSignature()
	})
}

// SetPathID sets the "path_id" field.
func (u *UploadTaskUpsertBulk) SetPathID(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetPathID(v)
	})
}

// UpdatePathID sets the "path_id" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdatePathID() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdatePathID()
	})
}

// SetTempDir sets the "temp_dir" field.
func (u *UploadTaskUpsertBulk) SetTempDir(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetTempDir(v)
	})
}

// UpdateTempDir sets the "temp_dir" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateTempDir() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateTempDir()
	})
}

// SetStatus sets the "status" field.
func (u *UploadTaskUpsertBulk) SetStatus(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateStatus() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UploadTaskUpsertBulk) SetErrorMessage(v string) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateErrorMessage() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UploadTaskUpsertBulk) ClearErrorMessage() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadTaskUpsertBulk) SetUpdatedAt(v time.Time) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateUpdatedAt() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadTaskUpsertBulk) SetExpiresAt(v time.Time) *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadTaskUpsertBulk) UpdateExpiresAt() *UploadTaskUpsertBulk {
	return u.Update(func(s *UploadTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *UploadTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UploadTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
