// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/uploadsession"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadSessionCreate is the builder for creating a UploadSession entity.
type UploadSessionCreate struct {
	config
	mutation *UploadSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDriveID sets the "drive_id" field.
func (_c *UploadSessionCreate) SetDriveID(v string) *UploadSessionCreate {
	_c.mutation.SetDriveID(v)
	return _c
}

// SetUploadID sets the "upload_id" field.
func (_c *UploadSessionCreate) SetUploadID(v string) *UploadSessionCreate {
	_c.mutation.SetUploadID(v)
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *UploadSessionCreate) SetFileID(v string) *UploadSessionCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetPartCount sets the "part_count" field.
func (_c *UploadSessionCreate) SetPartCount(v int) *UploadSessionCreate {
	_c.mutation.SetPartCount(v)
	return _c
}

// SetChunkSize sets the "chunk_size" field.
func (_c *UploadSessionCreate) SetChunkSize(v int64) *UploadSessionCreate {
	_c.mutation.SetChunkSize(v)
	return _c
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_c *UploadSessionCreate) SetNillableChunkSize(v *int64) *UploadSessionCreate {
	if v != nil {
		_c.SetChunkSize(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UploadSessionCreate) SetStatus(v uploadsession.Status) *UploadSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UploadSessionCreate) SetNillableStatus(v *uploadsession.Status) *UploadSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UploadSessionCreate) SetExpiresAt(v time.Time) *UploadSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UploadSessionCreate) SetNillableExpiresAt(v *time.Time) *UploadSessionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UploadSessionCreate) SetCreatedAt(v time.Time) *UploadSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UploadSessionCreate) SetNillableCreatedAt(v *time.Time) *UploadSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UploadSessionCreate) SetUpdatedAt(v time.Time) *UploadSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UploadSessionCreate) SetNillableUpdatedAt(v *time.Time) *UploadSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UploadSessionMutation object of the builder.
func (_c *UploadSessionCreate) Mutation() *UploadSessionMutation {
	return _c.mutation
}

// Save creates the UploadSession in the database.
func (_c *UploadSessionCreate) Save(ctx context.Context) (*UploadSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadSessionCreate) SaveX(ctx context.Context) *UploadSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadSessionCreate) defaults() {
	if _, ok := _c.mutation.ChunkSize(); !ok {
		v := uploadsession.DefaultChunkSize
		_c.mutation.SetChunkSize(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := uploadsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uploadsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := uploadsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadSessionCreate) check() error {
	if _, ok := _c.mutation.DriveID(); !ok {
		return &ValidationError{Name: "drive_id", err: errors.New(`ent: missing required field "UploadSession.drive_id"`)}
	}
	if v, ok := _c.mutation.DriveID(); ok {
		if err := uploadsession.DriveIDValidator(v); err != nil {
			return &ValidationError{Name: "drive_id", err: fmt.Errorf(`ent: validator failed for field "UploadSession.drive_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UploadID(); !ok {
		return &ValidationError{Name: "upload_id", err: errors.New(`ent: missing required field "UploadSession.upload_id"`)}
	}
	if v, ok := _c.mutation.UploadID(); ok {
		if err := uploadsession.UploadIDValidator(v); err != nil {
			return &ValidationError{Name: "upload_id", err: fmt.Errorf(`ent: validator failed for field "UploadSession.upload_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "UploadSession.file_id"`)}
	}
	if v, ok := _c.mutation.FileID(); ok {
		if err := uploadsession.FileIDValidator(v); err != nil {
			return &ValidationError{Name: "file_id", err: fmt.Errorf(`ent: validator failed for field "UploadSession.file_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PartCount(); !ok {
		return &ValidationError{Name: "part_count", err: errors.New(`ent: missing required field "UploadSession.part_count"`)}
	}
	if v, ok := _c.mutation.PartCount(); ok {
		if err := uploadsession.PartCountValidator(v); err != nil {
			return &ValidationError{Name: "part_count", err: fmt.Errorf(`ent: validator failed for field "UploadSession.part_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChunkSize(); !ok {
		return &ValidationError{Name: "chunk_size", err: errors.New(`ent: missing required field "UploadSession.chunk_size"`)}
	}
	if v, ok := _c.mutation.ChunkSize(); ok {
		if err := uploadsession.ChunkSizeValidator(v); err != nil {
			return &ValidationError{Name: "chunk_size", err: fmt.Errorf(`ent: validator failed for field "UploadSession.chunk_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UploadSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := uploadsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UploadSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UploadSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UploadSession.updated_at"`)}
	}
	return nil
}

func (_c *UploadSessionCreate) sqlSave(ctx context.Context) (*UploadSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadSessionCreate) createSpec() (*UploadSession, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadsession.Table, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DriveID(); ok {
		_spec.SetField(uploadsession.FieldDriveID, field.TypeString, value)
		_node.DriveID = value
	}
	if value, ok := _c.mutation.UploadID(); ok {
		_spec.SetField(uploadsession.FieldUploadID, field.TypeString, value)
		_node.UploadID = value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(uploadsession.FieldFileID, field.TypeString, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.PartCount(); ok {
		_spec.SetField(uploadsession.FieldPartCount, field.TypeInt, value)
		_node.PartCount = value
	}
	if value, ok := _c.mutation.ChunkSize(); ok {
		_spec.SetField(uploadsession.FieldChunkSize, field.TypeInt64, value)
		_node.ChunkSize = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(uploadsession.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uploadsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadSession.Create().
//		SetDriveID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadSessionUpsert) {
//			SetDriveID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadSessionCreate) OnConflict(opts ...sql.ConflictOption) *UploadSessionUpsertOne {
	_c.conflict = opts
	return &UploadSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadSessionCreate) OnConflictColumns(columns ...string) *UploadSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadSessionUpsertOne{
		create: _c,
	}
}

type (
	// UploadSessionUpsertOne is the builder for "upsert"-ing
	//  one UploadSession node.
	UploadSessionUpsertOne struct {
		create *UploadSessionCreate
	}

	// UploadSessionUpsert is the "OnConflict" setter.
	UploadSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetDriveID sets the "drive_id" field.
func (u *UploadSessionUpsert) SetDriveID(v string) *UploadSessionUpsert {
	u.Set(uploadsession.FieldDriveID, v)
	return u
}

// UpdateDriveID sets the "drive_id" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateDriveID() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldDriveID)
	return u
}

// SetFileID sets the "file_id" field.
func (u *UploadSessionUpsert) SetFileID(v string) *UploadSessionUpsert {
	u.Set(uploadsession.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateFileID() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldFileID)
	return u
}

// SetPartCount sets the "part_count" field.
func (u *UploadSessionUpsert) SetPartCount(v int) *UploadSessionUpsert {
	u.Set(uploadsession.FieldPartCount, v)
	return u
}

// UpdatePartCount sets the "part_count" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdatePartCount() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldPartCount)
	return u
}

// AddPartCount adds v to the "part_count" field.
func (u *UploadSessionUpsert) AddPartCount(v int) *UploadSessionUpsert {
	u.Add(uploadsession.FieldPartCount, v)
	return u
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadSessionUpsert) SetChunkSize(v int64) *UploadSessionUpsert {
	u.Set(uploadsession.FieldChunkSize, v)
	return u
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateChunkSize() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldChunkSize)
	return u
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadSessionUpsert) AddChunkSize(v int64) *UploadSessionUpsert {
	u.Add(uploadsession.FieldChunkSize, v)
	return u
}

// SetStatus sets the "status" field.
func (u *UploadSessionUpsert) SetStatus(v uploadsession.Status) *UploadSessionUpsert {
	u.Set(uploadsession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateStatus() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadSessionUpsert) SetExpiresAt(v time.Time) *UploadSessionUpsert {
	u.Set(uploadsession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateExpiresAt() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UploadSessionUpsert) ClearExpiresAt() *UploadSessionUpsert {
	u.SetNull(uploadsession.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadSessionUpsert) SetUpdatedAt(v time.Time) *UploadSessionUpsert {
	u.Set(uploadsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadSessionUpsert) UpdateUpdatedAt() *UploadSessionUpsert {
	u.SetExcluded(uploadsession.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UploadSessionUpsertOne) UpdateNewValues() *UploadSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.UploadID(); exists {
			s.SetIgnore(uploadsession.FieldUploadID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uploadsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UploadSessionUpsertOne) Ignore() *UploadSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadSessionUpsertOne) DoNothing() *UploadSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadSessionCreate.OnConflict
// documentation for more info.
func (u *UploadSessionUpsertOne) Update(set func(*UploadSessionUpsert)) *UploadSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDriveID sets the "drive_id" field.
func (u *UploadSessionUpsertOne) SetDriveID(v string) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetDriveID(v)
	})
}

// UpdateDriveID sets the "drive_id" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateDriveID() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateDriveID()
	})
}

// SetFileID sets the "file_id" field.
func (u *UploadSessionUpsertOne) SetFileID(v string) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateFileID() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateFileID()
	})
}

// SetPartCount sets the "part_count" field.
func (u *UploadSessionUpsertOne) SetPartCount(v int) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetPartCount(v)
	})
}

// AddPartCount adds v to the "part_count" field.
func (u *UploadSessionUpsertOne) AddPartCount(v int) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.AddPartCount(v)
	})
}

// UpdatePartCount sets the "part_count" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdatePartCount() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdatePartCount()
	})
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadSessionUpsertOne) SetChunkSize(v int64) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetChunkSize(v)
	})
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadSessionUpsertOne) AddChunkSize(v int64) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.AddChunkSize(v)
	})
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateChunkSize() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateChunkSize()
	})
}

// SetStatus sets the "status" field.
func (u *UploadSessionUpsertOne) SetStatus(v uploadsession.Status) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateStatus() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadSessionUpsertOne) SetExpiresAt(v time.Time) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateExpiresAt() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UploadSessionUpsertOne) ClearExpiresAt() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadSessionUpsertOne) SetUpdatedAt(v time.Time) *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadSessionUpsertOne) UpdateUpdatedAt() *UploadSessionUpsertOne {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UploadSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UploadSessionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UploadSessionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UploadSessionCreateBulk is the builder for creating many UploadSession entities in bulk.
type UploadSessionCreateBulk struct {
	config
	err      error
	builders []*UploadSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the UploadSession entities in the database.
func (_c *UploadSessionCreateBulk) Save(ctx context.Context) ([]*UploadSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadSessionCreateBulk) SaveX(ctx context.Context) []*UploadSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadSessionUpsert) {
//			SetDriveID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UploadSessionUpsertBulk {
	_c.conflict = opts
	return &UploadSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadSessionCreateBulk) OnConflictColumns(columns ...string) *UploadSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadSessionUpsertBulk{
		create: _c,
	}
}

// UploadSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of UploadSession nodes.
type UploadSessionUpsertBulk struct {
	create *UploadSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UploadSessionUpsertBulk) UpdateNewValues() *UploadSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.UploadID(); exists {
				s.SetIgnore(uploadsession.FieldUploadID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uploadsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UploadSessionUpsertBulk) Ignore() *UploadSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadSessionUpsertBulk) DoNothing() *UploadSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadSessionCreateBulk.OnConflict
// documentation for more info.
func (u *UploadSessionUpsertBulk) Update(set func(*UploadSessionUpsert)) *UploadSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDriveID sets the "drive_id" field.
func (u *UploadSessionUpsertBulk) SetDriveID(v string) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetDriveID(v)
	})
}

// UpdateDriveID sets the "drive_id" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateDriveID() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateDriveID()
	})
}

// SetFileID sets the "file_id" field.
func (u *UploadSessionUpsertBulk) SetFileID(v string) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateFileID() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateFileID()
	})
}

// SetPartCount sets the "part_count" field.
func (u *UploadSessionUpsertBulk) SetPartCount(v int) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetPartCount(v)
	})
}

// AddPartCount adds v to the "part_count" field.
func (u *UploadSessionUpsertBulk) AddPartCount(v int) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.AddPartCount(v)
	})
}

// UpdatePartCount sets the "part_count" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdatePartCount() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdatePartCount()
	})
}

// SetChunkSize sets the "chunk_size" field.
func (u *UploadSessionUpsertBulk) SetChunkSize(v int64) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetChunkSize(v)
	})
}

// AddChunkSize adds v to the "chunk_size" field.
func (u *UploadSessionUpsertBulk) AddChunkSize(v int64) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.AddChunkSize(v)
	})
}

// UpdateChunkSize sets the "chunk_size" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateChunkSize() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateChunkSize()
	})
}

// SetStatus sets the "status" field.
func (u *UploadSessionUpsertBulk) SetStatus(v uploadsession.Status) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateStatus() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UploadSessionUpsertBulk) SetExpiresAt(v time.Time) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateExpiresAt() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UploadSessionUpsertBulk) ClearExpiresAt() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadSessionUpsertBulk) SetUpdatedAt(v time.Time) *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadSessionUpsertBulk) UpdateUpdatedAt() *UploadSessionUpsertBulk {
	return u.Update(func(s *UploadSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UploadSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UploadSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
