// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/predicate"
	"molly-server/ent/uploadtask"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadTaskUpdate is the builder for updating UploadTask entities.
type UploadTaskUpdate struct {
	config
	hooks    []Hook
	mutation *UploadTaskMutation
}

// Where appends a list predicates to the UploadTaskUpdate builder.
func (_u *UploadTaskUpdate) Where(ps ...predicate.UploadTask) *UploadTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UploadTaskUpdate) SetUserID(v string) *UploadTaskUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableUserID(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *UploadTaskUpdate) SetFileName(v string) *UploadTaskUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableFileName(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadTaskUpdate) SetFileSize(v int64) *UploadTaskUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableFileSize(v *int64) *UploadTaskUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadTaskUpdate) AddFileSize(v int64) *UploadTaskUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadTaskUpdate) SetChunkSize(v int64) *UploadTaskUpdate {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableChunkSize(v *int64) *UploadTaskUpdate {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadTaskUpdate) AddChunkSize(v int64) *UploadTaskUpdate {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *UploadTaskUpdate) SetTotalChunks(v int) *UploadTaskUpdate {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableTotalChunks(v *int) *UploadTaskUpdate {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *UploadTaskUpdate) AddTotalChunks(v int) *UploadTaskUpdate {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (_u *UploadTaskUpdate) SetUploadedChunks(v int) *UploadTaskUpdate {
	_u.mutation.ResetUploadedChunks()
	_u.mutation.SetUploadedChunks(v)
	return _u
}

// SetNillableUploadedChunks sets the "uploaded_chunks" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableUploadedChunks(v *int) *UploadTaskUpdate {
	if v != nil {
		_u.SetUploadedChunks(*v)
	}
	return _u
}

// AddUploadedChunks adds value to the "uploaded_chunks" field.
func (_u *UploadTaskUpdate) AddUploadedChunks(v int) *UploadTaskUpdate {
	_u.mutation.AddUploadedChunks(v)
	return _u
}

// SetChunkSignature sets the "chunk_signature" field.
func (_u *UploadTaskUpdate) SetChunkSignature(v string) *UploadTaskUpdate {
	_u.mutation.SetChunkSignature(v)
	return _u
}

// SetNillableChunkSignature sets the "chunk_signature" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableChunkSignature(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetChunkSignature(*v)
	}
	return _u
}

// ClearChunkSignature clears the value of the "chunk_signature" field.
func (_u *UploadTaskUpdate) ClearChunkSignature() *UploadTaskUpdate {
	_u.mutation.ClearChunkSignature()
	return _u
}

// SetPathID sets the "path_id" field.
func (_u *UploadTaskUpdate) SetPathID(v string) *UploadTaskUpdate {
	_u.mutation.SetPathID(v)
	return _u
}

// SetNillablePathID sets the "path_id" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillablePathID(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetPathID(*v)
	}
	return _u
}

// SetTempDir sets the "temp_dir" field.
func (_u *UploadTaskUpdate) SetTempDir(v string) *UploadTaskUpdate {
	_u.mutation.SetTempDir(v)
	return _u
}

// SetNillableTempDir sets the "temp_dir" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableTempDir(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetTempDir(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadTaskUpdate) SetStatus(v string) *UploadTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableStatus(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UploadTaskUpdate) SetErrorMessage(v string) *UploadTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableErrorMessage(v *string) *UploadTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UploadTaskUpdate) ClearErrorMessage() *UploadTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadTaskUpdate) SetUpdatedAt(v time.Time) *UploadTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadTaskUpdate) SetExpiresAt(v time.Time) *UploadTaskUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadTaskUpdate) SetNillableExpiresAt(v *time.Time) *UploadTaskUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_u *UploadTaskUpdate) Mutation() *UploadTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UploadTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(uploadtask.Table, uploadtask.Columns, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(uploadtask.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(uploadtask.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadtask.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadtask.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadtask.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadtask.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(uploadtask.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(uploadtask.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedChunks(); ok {
		_spec.SetField(uploadtask.FieldUploadedChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedChunks(); ok {
		_spec.AddField(uploadtask.FieldUploadedChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSignature(); ok {
		_spec.SetField(uploadtask.FieldChunkSignature, field.TypeString, value)
	}
	if _u.mutation.ChunkSignatureCleared() {
		_spec.ClearField(uploadtask.FieldChunkSignature, field.TypeString)
	}
	if value, ok := _u.mutation.PathID(); ok {
		_spec.SetField(uploadtask.FieldPathID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TempDir(); ok {
		_spec.SetField(uploadtask.FieldTempDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(uploadtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(uploadtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadtask.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadTaskUpdateOne is the builder for updating a single UploadTask entity.
type UploadTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *UploadTaskUpdateOne) SetUserID(v string) *UploadTaskUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableUserID(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *UploadTaskUpdateOne) SetFileName(v string) *UploadTaskUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableFileName(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadTaskUpdateOne) SetFileSize(v int64) *UploadTaskUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableFileSize(v *int64) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadTaskUpdateOne) AddFileSize(v int64) *UploadTaskUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadTaskUpdateOne) SetChunkSize(v int64) *UploadTaskUpdateOne {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableChunkSize(v *int64) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadTaskUpdateOne) AddChunkSize(v int64) *UploadTaskUpdateOne {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *UploadTaskUpdateOne) SetTotalChunks(v int) *UploadTaskUpdateOne {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableTotalChunks(v *int) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *UploadTaskUpdateOne) AddTotalChunks(v int) *UploadTaskUpdateOne {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetUploadedChunks sets the "uploaded_chunks" field.
func (_u *UploadTaskUpdateOne) SetUploadedChunks(v int) *UploadTaskUpdateOne {
	_u.mutation.ResetUploadedChunks()
	_u.mutation.SetUploadedChunks(v)
	return _u
}

// SetNillableUploadedChunks sets the "uploaded_chunks" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableUploadedChunks(v *int) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetUploadedChunks(*v)
	}
	return _u
}

// AddUploadedChunks adds value to the "uploaded_chunks" field.
func (_u *UploadTaskUpdateOne) AddUploadedChunks(v int) *UploadTaskUpdateOne {
	_u.mutation.AddUploadedChunks(v)
	return _u
}

// SetChunkSignature sets the "chunk_signature" field.
func (_u *UploadTaskUpdateOne) SetChunkSignature(v string) *UploadTaskUpdateOne {
	_u.mutation.SetChunkSignature(v)
	return _u
}

// SetNillableChunkSignature sets the "chunk_signature" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableChunkSignature(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetChunkSignature(*v)
	}
	return _u
}

// ClearChunkSignature clears the value of the "chunk_signature" field.
func (_u *UploadTaskUpdateOne) ClearChunkSignature() *UploadTaskUpdateOne {
	_u.mutation.ClearChunkSignature()
	return _u
}

// SetPathID sets the "path_id" field.
func (_u *UploadTaskUpdateOne) SetPathID(v string) *UploadTaskUpdateOne {
	_u.mutation.SetPathID(v)
	return _u
}

// SetNillablePathID sets the "path_id" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillablePathID(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetPathID(*v)
	}
	return _u
}

// SetTempDir sets the "temp_dir" field.
func (_u *UploadTaskUpdateOne) SetTempDir(v string) *UploadTaskUpdateOne {
	_u.mutation.SetTempDir(v)
	return _u
}

// SetNillableTempDir sets the "temp_dir" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableTempDir(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetTempDir(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadTaskUpdateOne) SetStatus(v string) *UploadTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableStatus(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UploadTaskUpdateOne) SetErrorMessage(v string) *UploadTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableErrorMessage(v *string) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UploadTaskUpdateOne) ClearErrorMessage() *UploadTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadTaskUpdateOne) SetUpdatedAt(v time.Time) *UploadTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadTaskUpdateOne) SetExpiresAt(v time.Time) *UploadTaskUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadTaskUpdateOne) SetNillableExpiresAt(v *time.Time) *UploadTaskUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the UploadTaskMutation object of the builder.
func (_u *UploadTaskUpdateOne) Mutation() *UploadTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the UploadTaskUpdate builder.
func (_u *UploadTaskUpdateOne) Where(ps ...predicate.UploadTask) *UploadTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadTaskUpdateOne) Select(field string, fields ...string) *UploadTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UploadTask entity.
func (_u *UploadTaskUpdateOne) Save(ctx context.Context) (*UploadTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadTaskUpdateOne) SaveX(ctx context.Context) *UploadTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UploadTaskUpdateOne) sqlSave(ctx context.Context) (_node *UploadTask, err error) {
	_spec := sqlgraph.NewUpdateSpec(uploadtask.Table, uploadtask.Columns, sqlgraph.NewFieldSpec(uploadtask.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UploadTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadtask.FieldID)
		for _, f := range fields {
			if !uploadtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uploadtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(uploadtask.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(uploadtask.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadtask.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadtask.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadtask.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadtask.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(uploadtask.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(uploadtask.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedChunks(); ok {
		_spec.SetField(uploadtask.FieldUploadedChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedChunks(); ok {
		_spec.AddField(uploadtask.FieldUploadedChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChunkSignature(); ok {
		_spec.SetField(uploadtask.FieldChunkSignature, field.TypeString, value)
	}
	if _u.mutation.ChunkSignatureCleared() {
		_spec.ClearField(uploadtask.FieldChunkSignature, field.TypeString)
	}
	if value, ok := _u.mutation.PathID(); ok {
		_spec.SetField(uploadtask.FieldPathID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TempDir(); ok {
		_spec.SetField(uploadtask.FieldTempDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(uploadtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(uploadtask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadtask.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &UploadTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
