// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"molly-server/ent/uploadpart"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadPartCreate is the builder for creating a UploadPart entity.
type UploadPartCreate struct {
	config
	mutation *UploadPartMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUploadID sets the "upload_id" field.
func (_c *UploadPartCreate) SetUploadID(v string) *UploadPartCreate {
	_c.mutation.SetUploadID(v)
	return _c
}

// SetPartNumber sets the "part_number" field.
func (_c *UploadPartCreate) SetPartNumber(v int) *UploadPartCreate {
	_c.mutation.SetPartNumber(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *UploadPartCreate) SetSize(v int64) *UploadPartCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableSize(v *int64) *UploadPartCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetEtag sets the "etag" field.
func (_c *UploadPartCreate) SetEtag(v string) *UploadPartCreate {
	_c.mutation.SetEtag(v)
	return _c
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableEtag(v *string) *UploadPartCreate {
	if v != nil {
		_c.SetEtag(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UploadPartCreate) SetStatus(v uploadpart.Status) *UploadPartCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableStatus(v *uploadpart.Status) *UploadPartCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UploadPartCreate) SetCreatedAt(v time.Time) *UploadPartCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableCreatedAt(v *time.Time) *UploadPartCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UploadPartCreate) SetUpdatedAt(v time.Time) *UploadPartCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UploadPartCreate) SetNillableUpdatedAt(v *time.Time) *UploadPartCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UploadPartMutation object of the builder.
func (_c *UploadPartCreate) Mutation() *UploadPartMutation {
	return _c.mutation
}

// Save creates the UploadPart in the database.
func (_c *UploadPartCreate) Save(ctx context.Context) (*UploadPart, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadPartCreate) SaveX(ctx context.Context) *UploadPart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadPartCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadPartCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UploadPartCreate) defaults() {
	if _, ok := _c.mutation.Size(); !ok {
		v := uploadpart.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := uploadpart.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uploadpart.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := uploadpart.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadPartCreate) check() error {
	if _, ok := _c.mutation.UploadID(); !ok {
		return &ValidationError{Name: "upload_id", err: errors.New(`ent: missing required field "UploadPart.upload_id"`)}
	}
	if v, ok := _c.mutation.UploadID(); ok {
		if err := uploadpart.UploadIDValidator(v); err != nil {
			return &ValidationError{Name: "upload_id", err: fmt.Errorf(`ent: validator failed for field "UploadPart.upload_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PartNumber(); !ok {
		return &ValidationError{Name: "part_number", err: errors.New(`ent: missing required field "UploadPart.part_number"`)}
	}
	if v, ok := _c.mutation.PartNumber(); ok {
		if err := uploadpart.PartNumberValidator(v); err != nil {
			return &ValidationError{Name: "part_number", err: fmt.Errorf(`ent: validator failed for field "UploadPart.part_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "UploadPart.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := uploadpart.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "UploadPart.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UploadPart.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := uploadpart.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UploadPart.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UploadPart.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UploadPart.updated_at"`)}
	}
	return nil
}

func (_c *UploadPartCreate) sqlSave(ctx context.Context) (*UploadPart, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadPartCreate) createSpec() (*UploadPart, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadPart{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadpart.Table, sqlgraph.NewFieldSpec(uploadpart.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UploadID(); ok {
		_spec.SetField(uploadpart.FieldUploadID, field.TypeString, value)
		_node.UploadID = value
	}
	if value, ok := _c.mutation.PartNumber(); ok {
		_spec.SetField(uploadpart.FieldPartNumber, field.TypeInt, value)
		_node.PartNumber = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(uploadpart.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Etag(); ok {
		_spec.SetField(uploadpart.FieldEtag, field.TypeString, value)
		_node.Etag = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(uploadpart.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uploadpart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadpart.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadPart.Create().
//		SetUploadID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadPartUpsert) {
//			SetUploadID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadPartCreate) OnConflict(opts ...sql.ConflictOption) *UploadPartUpsertOne {
	_c.conflict = opts
	return &UploadPartUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadPartCreate) OnConflictColumns(columns ...string) *UploadPartUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadPartUpsertOne{
		create: _c,
	}
}

type (
	// UploadPartUpsertOne is the builder for "upsert"-ing
	//  one UploadPart node.
	UploadPartUpsertOne struct {
		create *UploadPartCreate
	}

	// UploadPartUpsert is the "OnConflict" setter.
	UploadPartUpsert struct {
		*sql.UpdateSet
	}
)

// SetUploadID sets the "upload_id" field.
func (u *UploadPartUpsert) SetUploadID(v string) *UploadPartUpsert {
	u.Set(uploadpart.FieldUploadID, v)
	return u
}

// UpdateUploadID sets the "upload_id" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdateUploadID() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldUploadID)
	return u
}

// SetPartNumber sets the "part_number" field.
func (u *UploadPartUpsert) SetPartNumber(v int) *UploadPartUpsert {
	u.Set(uploadpart.FieldPartNumber, v)
	return u
}

// UpdatePartNumber sets the "part_number" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdatePartNumber() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldPartNumber)
	return u
}

// AddPartNumber adds v to the "part_number" field.
func (u *UploadPartUpsert) AddPartNumber(v int) *UploadPartUpsert {
	u.Add(uploadpart.FieldPartNumber, v)
	return u
}

// SetSize sets the "size" field.
func (u *UploadPartUpsert) SetSize(v int64) *UploadPartUpsert {
	u.Set(uploadpart.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdateSize() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *UploadPartUpsert) AddSize(v int64) *UploadPartUpsert {
	u.Add(uploadpart.FieldSize, v)
	return u
}

// SetEtag sets the "etag" field.
func (u *UploadPartUpsert) SetEtag(v string) *UploadPartUpsert {
	u.Set(uploadpart.FieldEtag, v)
	return u
}

// UpdateEtag sets the "etag" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdateEtag() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldEtag)
	return u
}

// ClearEtag clears the value of the "etag" field.
func (u *UploadPartUpsert) ClearEtag() *UploadPartUpsert {
	u.SetNull(uploadpart.FieldEtag)
	return u
}

// SetStatus sets the "status" field.
func (u *UploadPartUpsert) SetStatus(v uploadpart.Status) *UploadPartUpsert {
	u.Set(uploadpart.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdateStatus() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadPartUpsert) SetUpdatedAt(v time.Time) *UploadPartUpsert {
	u.Set(uploadpart.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadPartUpsert) UpdateUpdatedAt() *UploadPartUpsert {
	u.SetExcluded(uploadpart.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UploadPartUpsertOne) UpdateNewValues() *UploadPartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uploadpart.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UploadPartUpsertOne) Ignore() *UploadPartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadPartUpsertOne) DoNothing() *UploadPartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadPartCreate.OnConflict
// documentation for more info.
func (u *UploadPartUpsertOne) Update(set func(*UploadPartUpsert)) *UploadPartUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadPartUpsert{UpdateSet: update})
	}))
	return u
}

// SetUploadID sets the "upload_id" field.
func (u *UploadPartUpsertOne) SetUploadID(v string) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetUploadID(v)
	})
}

// UpdateUploadID sets the "upload_id" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdateUploadID() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateUploadID()
	})
}

// SetPartNumber sets the "part_number" field.
func (u *UploadPartUpsertOne) SetPartNumber(v int) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetPartNumber(v)
	})
}

// AddPartNumber adds v to the "part_number" field.
func (u *UploadPartUpsertOne) AddPartNumber(v int) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.AddPartNumber(v)
	})
}

// UpdatePartNumber sets the "part_number" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdatePartNumber() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdatePartNumber()
	})
}

// SetSize sets the "size" field.
func (u *UploadPartUpsertOne) SetSize(v int64) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *UploadPartUpsertOne) AddSize(v int64) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdateSize() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateSize()
	})
}

// SetEtag sets the "etag" field.
func (u *UploadPartUpsertOne) SetEtag(v string) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetEtag(v)
	})
}

// UpdateEtag sets the "etag" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdateEtag() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateEtag()
	})
}

// ClearEtag clears the value of the "etag" field.
func (u *UploadPartUpsertOne) ClearEtag() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.ClearEtag()
	})
}

// SetStatus sets the "status" field.
func (u *UploadPartUpsertOne) SetStatus(v uploadpart.Status) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdateStatus() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadPartUpsertOne) SetUpdatedAt(v time.Time) *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadPartUpsertOne) UpdateUpdatedAt() *UploadPartUpsertOne {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UploadPartUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadPartCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadPartUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UploadPartUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UploadPartUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UploadPartCreateBulk is the builder for creating many UploadPart entities in bulk.
type UploadPartCreateBulk struct {
	config
	err      error
	builders []*UploadPartCreate
	conflict []sql.ConflictOption
}

// Save creates the UploadPart entities in the database.
func (_c *UploadPartCreateBulk) Save(ctx context.Context) ([]*UploadPart, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadPart, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadPartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadPartCreateBulk) SaveX(ctx context.Context) []*UploadPart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadPartCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadPartCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UploadPart.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UploadPartUpsert) {
//			SetUploadID(v+v).
//		}).
//		Exec(ctx)
func (_c *UploadPartCreateBulk) OnConflict(opts ...sql.ConflictOption) *UploadPartUpsertBulk {
	_c.conflict = opts
	return &UploadPartUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UploadPartCreateBulk) OnConflictColumns(columns ...string) *UploadPartUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UploadPartUpsertBulk{
		create: _c,
	}
}

// UploadPartUpsertBulk is the builder for "upsert"-ing
// a bulk of UploadPart nodes.
type UploadPartUpsertBulk struct {
	create *UploadPartCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UploadPartUpsertBulk) UpdateNewValues() *UploadPartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uploadpart.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UploadPart.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UploadPartUpsertBulk) Ignore() *UploadPartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UploadPartUpsertBulk) DoNothing() *UploadPartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UploadPartCreateBulk.OnConflict
// documentation for more info.
func (u *UploadPartUpsertBulk) Update(set func(*UploadPartUpsert)) *UploadPartUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UploadPartUpsert{UpdateSet: update})
	}))
	return u
}

// SetUploadID sets the "upload_id" field.
func (u *UploadPartUpsertBulk) SetUploadID(v string) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetUploadID(v)
	})
}

// UpdateUploadID sets the "upload_id" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdateUploadID() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateUploadID()
	})
}

// SetPartNumber sets the "part_number" field.
func (u *UploadPartUpsertBulk) SetPartNumber(v int) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetPartNumber(v)
	})
}

// AddPartNumber adds v to the "part_number" field.
func (u *UploadPartUpsertBulk) AddPartNumber(v int) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.AddPartNumber(v)
	})
}

// UpdatePartNumber sets the "part_number" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdatePartNumber() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdatePartNumber()
	})
}

// SetSize sets the "size" field.
func (u *UploadPartUpsertBulk) SetSize(v int64) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *UploadPartUpsertBulk) AddSize(v int64) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdateSize() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateSize()
	})
}

// SetEtag sets the "etag" field.
func (u *UploadPartUpsertBulk) SetEtag(v string) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetEtag(v)
	})
}

// UpdateEtag sets the "etag" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdateEtag() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateEtag()
	})
}

// ClearEtag clears the value of the "etag" field.
func (u *UploadPartUpsertBulk) ClearEtag() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.ClearEtag()
	})
}

// SetStatus sets the "status" field.
func (u *UploadPartUpsertBulk) SetStatus(v uploadpart.Status) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdateStatus() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UploadPartUpsertBulk) SetUpdatedAt(v time.Time) *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UploadPartUpsertBulk) UpdateUpdatedAt() *UploadPartUpsertBulk {
	return u.Update(func(s *UploadPartUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UploadPartUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UploadPartCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UploadPartCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UploadPartUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
