// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"molly-server/ent/predicate"
	"molly-server/ent/uploadsession"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadSessionDelete is the builder for deleting a UploadSession entity.
type UploadSessionDelete struct {
	config
	hooks    []Hook
	mutation *UploadSessionMutation
}

// Where appends a list predicates to the UploadSessionDelete builder.
func (_d *UploadSessionDelete) Where(ps ...predicate.UploadSession) *UploadSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UploadSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UploadSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UploadSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(uploadsession.Table, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UploadSessionDeleteOne is the builder for deleting a single UploadSession entity.
type UploadSessionDeleteOne struct {
	_d *UploadSessionDelete
}

// Where appends a list predicates to the UploadSessionDelete builder.
func (_d *UploadSessionDeleteOne) Where(ps ...predicate.UploadSession) *UploadSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UploadSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uploadsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UploadSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
