// Code generated by ent, DO NOT EDIT.

package virtualpath

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the virtualpath type in the database.
	Label = "virtual_path"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldIsFile holds the string denoting the is_file field in the database.
	FieldIsFile = "is_file"
	// FieldIsDir holds the string denoting the is_dir field in the database.
	FieldIsDir = "is_dir"
	// FieldParentLevel holds the string denoting the parent_level field in the database.
	FieldParentLevel = "parent_level"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_time"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "update_time"
	// Table holds the table name of the virtualpath in the database.
	Table = "virtual_path"
)

// Columns holds all SQL columns for virtualpath fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPath,
	FieldIsFile,
	FieldIsDir,
	FieldParentLevel,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsFile holds the default value on creation for the "is_file" field.
	DefaultIsFile bool
	// DefaultIsDir holds the default value on creation for the "is_dir" field.
	DefaultIsDir bool
	// DefaultParentLevel holds the default value on creation for the "parent_level" field.
	DefaultParentLevel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VirtualPath queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByIsFile orders the results by the is_file field.
func ByIsFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFile, opts...).ToFunc()
}

// ByIsDir orders the results by the is_dir field.
func ByIsDir(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDir, opts...).ToFunc()
}

// ByParentLevel orders the results by the parent_level field.
func ByParentLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentLevel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
