// Code generated by ent, DO NOT EDIT.

package s3bucketpolicy

import (
	"molly-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldID, id))
}

// BucketName applies equality check predicate on the "bucket_name" field. It's identical to BucketNameEQ.
func BucketName(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldBucketName, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldUserID, v))
}

// PolicyJSON applies equality check predicate on the "policy_json" field. It's identical to PolicyJSONEQ.
func PolicyJSON(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldPolicyJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// BucketNameEQ applies the EQ predicate on the "bucket_name" field.
func BucketNameEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldBucketName, v))
}

// BucketNameNEQ applies the NEQ predicate on the "bucket_name" field.
func BucketNameNEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldBucketName, v))
}

// BucketNameIn applies the In predicate on the "bucket_name" field.
func BucketNameIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldBucketName, vs...))
}

// BucketNameNotIn applies the NotIn predicate on the "bucket_name" field.
func BucketNameNotIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldBucketName, vs...))
}

// BucketNameGT applies the GT predicate on the "bucket_name" field.
func BucketNameGT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldBucketName, v))
}

// BucketNameGTE applies the GTE predicate on the "bucket_name" field.
func BucketNameGTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldBucketName, v))
}

// BucketNameLT applies the LT predicate on the "bucket_name" field.
func BucketNameLT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldBucketName, v))
}

// BucketNameLTE applies the LTE predicate on the "bucket_name" field.
func BucketNameLTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldBucketName, v))
}

// BucketNameContains applies the Contains predicate on the "bucket_name" field.
func BucketNameContains(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContains(FieldBucketName, v))
}

// BucketNameHasPrefix applies the HasPrefix predicate on the "bucket_name" field.
func BucketNameHasPrefix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasPrefix(FieldBucketName, v))
}

// BucketNameHasSuffix applies the HasSuffix predicate on the "bucket_name" field.
func BucketNameHasSuffix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasSuffix(FieldBucketName, v))
}

// BucketNameEqualFold applies the EqualFold predicate on the "bucket_name" field.
func BucketNameEqualFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEqualFold(FieldBucketName, v))
}

// BucketNameContainsFold applies the ContainsFold predicate on the "bucket_name" field.
func BucketNameContainsFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContainsFold(FieldBucketName, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContainsFold(FieldUserID, v))
}

// PolicyJSONEQ applies the EQ predicate on the "policy_json" field.
func PolicyJSONEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldPolicyJSON, v))
}

// PolicyJSONNEQ applies the NEQ predicate on the "policy_json" field.
func PolicyJSONNEQ(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldPolicyJSON, v))
}

// PolicyJSONIn applies the In predicate on the "policy_json" field.
func PolicyJSONIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldPolicyJSON, vs...))
}

// PolicyJSONNotIn applies the NotIn predicate on the "policy_json" field.
func PolicyJSONNotIn(vs ...string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldPolicyJSON, vs...))
}

// PolicyJSONGT applies the GT predicate on the "policy_json" field.
func PolicyJSONGT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldPolicyJSON, v))
}

// PolicyJSONGTE applies the GTE predicate on the "policy_json" field.
func PolicyJSONGTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldPolicyJSON, v))
}

// PolicyJSONLT applies the LT predicate on the "policy_json" field.
func PolicyJSONLT(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldPolicyJSON, v))
}

// PolicyJSONLTE applies the LTE predicate on the "policy_json" field.
func PolicyJSONLTE(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldPolicyJSON, v))
}

// PolicyJSONContains applies the Contains predicate on the "policy_json" field.
func PolicyJSONContains(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContains(FieldPolicyJSON, v))
}

// PolicyJSONHasPrefix applies the HasPrefix predicate on the "policy_json" field.
func PolicyJSONHasPrefix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasPrefix(FieldPolicyJSON, v))
}

// PolicyJSONHasSuffix applies the HasSuffix predicate on the "policy_json" field.
func PolicyJSONHasSuffix(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldHasSuffix(FieldPolicyJSON, v))
}

// PolicyJSONEqualFold applies the EqualFold predicate on the "policy_json" field.
func PolicyJSONEqualFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEqualFold(FieldPolicyJSON, v))
}

// PolicyJSONContainsFold applies the ContainsFold predicate on the "policy_json" field.
func PolicyJSONContainsFold(v string) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldContainsFold(FieldPolicyJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.S3BucketPolicy) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.S3BucketPolicy) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.S3BucketPolicy) predicate.S3BucketPolicy {
	return predicate.S3BucketPolicy(sql.NotPredicates(p))
}
